### ISSUE TITLE
Lazy loading?

### ISSUE THREAD

**Issue by oyeanuj** [sag1v/react-elastic-carousel#10]
**Is your feature request related to a problem? Please describe.**
I'm using the carousel for showcasing some posts, and would like to lazy load to not make the page be bombarding requests. 

**Describe the solution you'd like**
 I'm wondering if that is possible with the current props in the library, if it should be part of the library or if there is a specific way non-library way that you'd recommend?

**Describe alternatives you've considered**
External libraries maybe that will lazy-load when in view, but I feel like this might be a thing that could be part of the library.

**Comment by sag1v** [comment]
Sounds interesting, so you mean instead of passing portion of the children to `react-elastic-carousel` you suggests that the library will render just the visible items (maybe with 1 or more on start and end positions)?

**Comment by sag1v** [comment]
FYI, you can do it yourself outside the library.  
Just pass the number of items you want, and add more items  with the `onNextStart` hook.  

See [example](https://codesandbox.io/s/xpkkpnj91p)

**Code snippet:** 

```
class App extends React.Component {
  state = {
    items: [1, 2, 3, 4]
  };

  addItem = ({ index, item }) => {
    console.log(index, item);
    this.setState(({ items }) => {
      if (items.length > index + 3) {
        // ensure that we only add 3 items ahead
        return null;
      }
      const newItem = items.length + 1;
      const nextItems = [...items, newItem];
      return {
        items: nextItems
      };
    });
  };

  render() {
    const { items } = this.state;
    return (
      <div className="App">
        <Carousel onNextStart={this.addItem}>
          {items.map(item => <Item key={item}>{item}</Item>)}
        </Carousel>
      </div>
    );
  }
}
```
I'm closing this issue as it is doable outside the library.  
If you think this should be re-opened feel free to re-open the issue and elaborate on the challenge.

**Comment by oyeanuj** [comment]
@sag1v Oh, that's really interesting technique. I didn't think of using `onNextStart`. The only challenge that I can now see is that if you are having multiple elements in view at any given time, then you might have to do some duplicate responsive calculation based on the width, to determine how many to add to the carousel. 

For example, if we start with 5 elements for the widest case, we might be loading too much for the mobile screen? Since the library is handling some responsiveness logic, is there a way for us to make use of that?

**Comment by sag1v** [comment]
You can can get the current `breakPoint` with the `onResize` hook. https://sag1v.github.io/react-elastic-carousel/#/onResize
