### ISSUE TITLE
How do i detect middle item

### ISSUE THREAD

**Issue by hungdev** [sag1v/react-elastic-carousel#100]
Your lib so nice but i have a question.
is there anyway to know is the middle item? via css property or props...
for example: first slide, we have 1,2,3. Second slide: 4,5,6. so i want to detect item 2 of first slide, and 5 of second slide.
Because when i get the middle item of silde, i can make css for it.

**Comment by sag1v** [comment]
Hi, thanks. 

Well you can achieve that with a simple math and tracking the current index.
Keep in mind that there is only a middle if you have an odd number of `itemsToShow` :)

All you need is to keep track on current index and calculate the middle based on the `itemsToShow` you provided and current index.

e.g:

```js
const mid = Math.ceil(itemsToShow / 2) - 1;
const nextMid = mid + nextIndex;
```

Here is a full example:

```jsx
const items = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
const itemsToShow = 3;
const getMid = () => Math.ceil(itemsToShow / 2) - 1; // 0 based
function App() {
  const [midItemIndex, setMidItemIndex] = useState(getMid);

  const onChange = (_, next) => {
    const mid = getMid();
    setMidItemIndex(mid + next.index);
  };

  return (
    <div>
      <Carousel
        itemsToShow={itemsToShow}
        onNextStart={onChange}
        onPrevStart={onChange}
      >
        {items.map((item, idx) => (
          <Item
            style={{
              boxShadow: midItemIndex === idx  ? "0 0 5px 5px #333" : ""
            }}
            key={item}
          >
            {item}
          </Item>
        ))}
      </Carousel>
    </div>
  );
}
```

**Comment by hungdev** [comment]
Great, That's what I need <3
thank you.
