### ISSUE TITLE
Default align center of cards not working

### ISSUE THREAD

**Issue by AK5123** [sag1v/react-elastic-carousel#102]
When items to display is 2 or more and if only one card is available in the list it is positioning to left, rather aligning center.
![not_center](https://user-images.githubusercontent.com/43901655/98036100-7636ae00-1e3f-11eb-9d40-9db05e82e2ef.png)

**Comment by hungdev** [comment]
I think you should check number of Item then set itemsToShow value

**Comment by AK5123** [comment]
Yes, but I need to have a responsive slider for which I used breakpoints and each breakpoint already has specific items to show. Now customising each of items to show based on no of cards doesn't look good.

**Comment by sag1v** [comment]
Hi, thanks.
I'm trying to think about a use case where someone will want that empty slots when `itemsToShow` are greater than `children.length`. And if there is a use case, what is the best API to support both use cases: No empty slots and with empty slots?

**Comment by sag1v** [comment]
Fixed as of `v0.9.4`

**Comment by CannelleRb** [comment]
well... I needed empty slots... I'm going to submit a PR to add a "showEmptySlots" parameter :(

**Comment by CannelleRb** [comment]
-> #114
