### ISSUE TITLE
Padding on slider sides

### ISSUE THREAD

**Issue by CannelleRb** [sag1v/react-elastic-carousel#103]
Hello, I need to put some left and right padding on the rec-slider div (at the beginning and the end of the items' list), but I couldn't do it without breaking everything.
Could you please add a prop enabling us to do that ? Another solution would be to change the itemPadding prop so that it can have a different value for the first and last item, for example.
Thank you :)

**Comment by sag1v** [comment]
Hi, You have a public `CSS` class for each element of the carousel ([more info](https://sag1v.github.io/react-elastic-carousel/#styling)). In this case you probably want to style the `container`.
Instead of padding though, i would go with margin.

For example:

```css
.rec.rec-slider-container {
    margin: 0 100px;
}
```

**Comment by CannelleRb** [comment]
Hello, thanks for your quick answer :) I already tried this solution, but I don't get the result I want with it... I drew a quick blueprint of what you suggested (the first row) and what I need (the second row):
![image](https://user-images.githubusercontent.com/28741188/98545811-5287c380-2296-11eb-9157-d59e0ea061c8.png)
Here is a real life example, which is from Netflix:
![image](https://user-images.githubusercontent.com/28741188/98545896-74814600-2296-11eb-90c9-46d0138d35ac.png)
Thanks a lot :)
Have a nice day !

**Comment by sag1v** [comment]
Not sure i understand but i think you are after a decimal items to show.
For example:
`itemsToShow: 3.5`

**Comment by CannelleRb** [comment]
No, I would like to have a margin (or a padding) at the beginning and at the end of the scrolled row :) For example on this carousel here (which is not react-elastic-carousel), I have a padding at the beginning and at the end, as shown in this gif:
![with another carousel](https://user-images.githubusercontent.com/28741188/98570350-a654d580-22b3-11eb-97d0-1e43ddf3c309.gif)
As you can see, the right padding only appears when the carousel is completely scrolled to the right, and indicates I'm done scrolling.

but when I try to do that with react-elastic-carousel, the carousel is cropped at the end (probably because I added the padding manually and the width was computed beforehand)
![with react-elastic-carousel](https://user-images.githubusercontent.com/28741188/98570366-a94fc600-22b3-11eb-9997-31ec6ff7efc9.gif)

**Comment by sag1v** [comment]
Can you create a small PR with your suggested solution?

**Comment by CannelleRb** [comment]
-> #114

**Comment by sag1v** [comment]
resolved with #123
