### ISSUE TITLE
RTL scrolling issue

### ISSUE THREAD

**Issue by anns-seera** [sag1v/react-elastic-carousel#109]
**Describe the bug**
When scrolling/swipping on RTL carousel the item first go left and then right. this is strange.

I am using react-elastic-carousel **version 0.9.3**

**Comment by sag1v** [comment]
Thanks @anns-seera .
It only happens with swipe not when using the buttons right?
I think its a bug from a recent change i made to the swiping mechanism. I will fix it soon.

**Comment by sag1v** [comment]
@anns-seera Can you test this version please? `0.9.5-beta.2`.
When you confirm this is fixed i will merge to master and publish it.

**Comment by anns-seera** [comment]
Sure, i'm checking.

**Comment by anns-seera** [comment]
Its working fine now.

**Comment by sag1v** [comment]
Fixed as of version `0.9.5`

Thanks for the catch!
