### ISSUE TITLE
Add compatability for styled-components 4

### ISSUE THREAD

**Issue by garth** [sag1v/react-elastic-carousel#11]
**Is your feature request related to a problem? Please describe.**

`styled-components` 4 has changed they way refs are retrieved.

> The "innerRef" API has been removed in styled-components v4 in favor of React 16 ref forwarding, use "ref" instead like a typical component.

Since `react-elastic-carousel` uses `styled-components` 3, it's not currently possible to use `react-elastic-carousel` within a project that depends on `styled-components` 4.

**Describe the solution you'd like**

Either update `styled-components` or remove it as a dependency.

**Comment by sag1v** [comment]
Thank you.
Done with in [v0.2.0](https://github.com/sag1v/react-elastic-carousel/commit/d189c925e67b44db05df66d4c0eb5da48800f3cd).  
Can you confirm its working well for you?

**Comment by garth** [comment]
@sag1v it works great, thanks for the fast turnaround!
