### ISSUE TITLE
Breakpoints on vertical mode

### ISSUE THREAD

**Issue by roidersp** [sag1v/react-elastic-carousel#115]
**Is your feature request related to a problem? Please describe.**
I need show as items as posible on container in vertical mode

**Describe the solution you'd like**
add height support on breakpoints 

`this.breakPoints = [
        { height: 1, itemsToShow: 1 },
        { height: 550, itemsToShow: 2, itemsToScroll: 2, pagination: false },
        { height: 850, itemsToShow: 3 },
        { height: 1150, itemsToShow: 4, itemsToScroll: 2 },
        { height: 1450, itemsToShow: 5 },
        { height: 1750, itemsToShow: 6 },
      ]`

**Describe alternatives you've considered**

**Additional context**

**Comment by sag1v** [comment]
@roidersp Thanks. 
Any suggested solution? a PR is always welcome! :)
