### ISSUE TITLE
Improved Pagination Configuration - Dot Per Item/Slide Instead of Per Page

### ISSUE THREAD

**Issue by chris2fr** [sag1v/react-elastic-carousel#118]
**Is your feature request related to a problem? Please describe.**

I would like the dots of pagination not to reflect the pages, but rather the focused slides themselves.

**Describe the solution you'd like**

paginationPerSlide={false} or {true}

**Describe alternatives you've considered**

renderPagination, but that doesn't work. I am not sure I have all the information available.

**Additional context**

This is partially to compensate the Mouse-Down bug. #117

**Comment by sag1v** [comment]
@chris2fr Thanks.
Well, pagination as the name suggests, is about displaying a bulk of items.
What you need here is a duplicate list of all items that renders some buttons, so basically you can just loop over your items and create elements that have an `onClick` handler that triggers the [goTo](https://sag1v.github.io/react-elastic-carousel/goTo) method.

For example:
```jsx
function App() {
  // if you want an indicator of active button we need to keep track of selected item
  const [activeItemIndex, setActiveItemIndex] = useState(0);
  // get a ref to carousel in order to trigger the goTo handler
  const carouselRef = useRef();

  return (
    <div>
      <Carousel
        ref={carouselRef}
        pagination={false}
        onChange={(currentItem) => setActiveItemIndex(currentItem.index)}
      >
        {items.map((item, i) => (
          <Item key={i}>{item}</Item>
        ))}
      </Carousel>
      <div style={{ display: "flex", justifyContent: "center" }}>
        {items.map((_, i) => (
          <Button
            key={i}
            active={i === activeItemIndex}
            onClick={() => carouselRef.current.goTo(i)}
          />
        ))}
      </div>
    </div>
  );
}
```

Here is a sandbox example [link](https://codesandbox.io/s/react-elastic-carousel-forked-hc5ye?file=/src/index.js:487-1311)

**Comment by chris2fr** [comment]
THANK YOU SO MUCH
You are able to clear up in this code how to work with refs between elements on a react page, but I wonder if it works in Gatsby.
TBC
I would just make one change. The number of items on the slide paginator would be n - carousel.itemsToShow or there may be some outer-rectangle around the inner-dots.

**Comment by sag1v** [comment]
Gatsby should work the same for refs AFAIK.
As for the calculation, why do you want to reduce the itemsToShow?

**Comment by chris2fr** [comment]
With 3 itemsToShow and 10 slides, I can only go to position 7. 
Here is what I think is the way to go:

https://codesandbox.io/s/react-elastic-carousel-forked-5hziq?file=/src/index.js

**Comment by sag1v** [comment]
Well if that works for you then great 🙂

**Comment by sag1v** [comment]
So can we close this one?
