### ISSUE TITLE
Remove Styled Components Dependency

### ISSUE THREAD

**Issue by chris2fr** [sag1v/react-elastic-carousel#119]
**Is your feature request related to a problem? Please describe.**

I would like to understand where the styles come from.

**Describe the solution you'd like**

I would like move the styled-components styles to the stylesheets, please.

**Describe alternatives you've considered**

Forking maybe, but that would be a little silly for such a small thing.

**Additional context**

Do we need styled-components?

**Comment by sag1v** [comment]
Hi, the styles are applied via styled-components, if you want to override styling you can use the [public class names](https://sag1v.github.io/react-elastic-carousel/#styling)

**Comment by Zn4rK** [comment]
As much as I love `styled-components` I love `@emotion/styled` more, and I don't want both.

I think it might be a good idea to re-evaluate the need to apply base styles via styled-components.

**Comment by sag1v** [comment]
> As much as I love `styled-components` I love `@emotion/styled` more, and I don't want both.
> 
> I think it might be a good idea to re-evaluate the need to apply base styles via styled-components.

Yeah this decision is getting some heat 😬

The idea was to not force consumers to import or include the lib's css file. 

What if we go with styled JSS, can i use it as a regular dependency and it won't conflict with the consumer's jss libraries (if present)?

https://cssinjs.org/styled-jss?v=v2.2.3
