### ISSUE TITLE
How can I style the indicators when active and not active state. 

### ISSUE THREAD

**Issue by gfunk1230** [sag1v/react-elastic-carousel#12]
I was wondering how I can style the indicators on the carousel. I see I can style the indicator itself by using the classname .rec.rec-dot but I was wondering how can i change the style of the indicator when its active? Thanks

**Comment by gfunk1230** [comment]
![image](https://user-images.githubusercontent.com/6556242/53281664-97527c00-36fa-11e9-9178-b6b02760e7a6.png)

**Comment by gfunk1230** [comment]
@sag1v Hope that makes sense hopefully can be done. thanks

**Comment by sag1v** [comment]
@gfunk1230 As you can see [here](https://github.com/sag1v/react-elastic-carousel/blob/master/src/react-elastic-carousel/components/Pagination/Dot.js#L39) we are not adding an `active` class.
A possible change might be something like this: 
```
<Dot
  onClick={this.onClick}
  active={active}
  className={`${cssPrefix("dot")} ${active ? cssPrefix("dot_active") : '' }`}
/>
```
Or, you can just create your own pagination indicator. you can see more details about it [here](https://sag1v.github.io/react-elastic-carousel/#/renderPagination)

**Comment by gfunk1230** [comment]
@sag1v awesome! thanks so much for the quick reply

**Comment by sag1v** [comment]
@gfunk1230 Do you want to PR with this change?

**Comment by sag1v** [comment]
@orensurf

**Comment by gfunk1230** [comment]
@sag1v just to be clear you would like me to create this enhancement myself and commit a PR for it?

**Comment by gfunk1230** [comment]
@sag1v if so it seems like the suggested above should be easy to implement.

``js 
<Dot
  onClick={this.onClick}
  active={active}
  className={`${cssPrefix("dot")} ${active ? cssPrefix("dot_active") : '' }`}
/>

**Comment by gfunk1230** [comment]
@sag1v any chance you can make that update actually since i am getting failing test when trying to commit the PR. It would be greatly appreciated. 

![image](https://user-images.githubusercontent.com/6556242/53460189-40a2b600-3a0a-11e9-888c-a9273424a183.png)

**Comment by sag1v** [comment]
Interesting, i saw [this issue](https://github.com/facebook/jest/issues/6393). I will try to check it later on.

**Comment by sag1v** [comment]
@gfunk1230 Indeed there was a problem with `jest-cli` i did `npm uninstall jest-cli` and tests are running fine now. see #13 
You can pull the latest changes i made and try it yourself, and of course commit the PR. :smile:

**Comment by sag1v** [comment]
@orensurf You can try now, i switched to yarn instead of npm because npm has some issues with linked dependencies.
1. Get my latest commits from master ([git pull](https://help.github.com/en/articles/fetching-a-remote))
2. Delete `node_modules`
3. Run `yarn`
4. Then run `yarn docz:dev` to run the app.

**Comment by waheed7429** [comment]
how can i disable dots of elastic carousel i dontnwant to show them

**Comment by sag1v** [comment]
@waheed7429 You can pass `pagination: false`
