### ISSUE TITLE
Animation type

### ISSUE THREAD

**Issue by Luisdv93** [sag1v/react-elastic-carousel#120]
**Is your feature request related to a problem? Please describe.**
I read the docs but I couldn't find an option to define the animation type, I really like this library but it seems to be missing a way to define one besides sliding, for example a fade in and out. 

**Describe the solution you'd like**
`
<Carousel itemsToShow={1} animationType="fade"></Carousel>`

**Comment by sag1v** [comment]
@Luisdv93 Thanks. So you say a fade animation instead of sliding, so how will the items change places?

**Comment by Luisdv93** [comment]
@sag1v Bear in my mind I haven't looked too deep into it, but from what I saw the library works by calculating a total width of the Carousel by summing the width of the childrens right? I didn't check the source code so I could be wrong. In a fade animation the items would change places by lowering the opacity of the current item to 0 and next one to 1.

**Comment by sag1v** [comment]
Opacity alone won't make them change places so i guess its not instead of sliding but in addition right?

**Comment by Luisdv93** [comment]
Yes, sliding could be the default behaviour and the fade could be another type of animation for it. You can see an example of how it looks here: https://learus.github.io/react-material-ui-carousel/

**Comment by sag1v** [comment]
Interesting, my initial thought is that i would like to support any kind of animation provided by the consumer, so we wont need to implement animations per request. Like if one wants `transform:scale()` or fade in/out or whatever people will need in the future.
But this is tricky, we will need to allow the consumer to hook into the before change event, but also we will need to wait until the animation is over before we transition to the next slide. 
I will think further about this, if you got any ideas please share :)

**Comment by caseyjhol** [comment]
This issue should not be closed.
