### ISSUE TITLE
Add padding above the items

### ISSUE THREAD

**Issue by claytron5000** [sag1v/react-elastic-carousel#121]
**Is your feature request related to a problem? Please describe.**
I'd like to add a coloured background behind the slides, but not the arrows, and have colored space above each slide. I can add the background to the `.rec-slider-container`. However, because the `.rec-carousel` element has inlined height, adding vertical padding pushes the slides downward.

Requested display:
![image](https://user-images.githubusercontent.com/5767672/100017659-40834600-2da9-11eb-99ab-265c369bdee2.png)

Current display:
![image](https://user-images.githubusercontent.com/5767672/100017552-1467c500-2da9-11eb-94ba-6dd1b736c1fa.png)

**Describe the solution you'd like**
I would like to be able adjust the height of the slider.

**Describe alternatives you've considered**
I've tried:
- using a ref to get the DOM element and set its height after initial render
- color the `.rec-carousel-wrapper` and position the arrows absolutely (this is my preferred solution at the moment)

**Comment by sag1v** [comment]
@claytron5000 Thanks.
In addition to the background that you add to `.rec.rec-slider-container` you can pass the [itemPadding](https://sag1v.github.io/react-elastic-carousel/itemPadding) prop.

So you css might look something like:

```css
.rec.rec-slider-container {
    background-color: #aaa;
}
```

And jsx:

```jsx
<Carousel itemPadding={[10]} itemsToShow={3}>
...
</Carousel>
```

**Comment by claytron5000** [comment]
I totally missed that property, thanks!
