### ISSUE TITLE
Slider doesn't reconfigure when browser window is resized.

### ISSUE THREAD

**Issue by ChildishhAlbino** [sag1v/react-elastic-carousel#122]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a Carousel with 3 items that shows n items
2. shrink the browser window to a point where you show less than n items
3. advance the list one stage
4. fullscreen the browser window

**Expected behaviour**
The slider should responsively update to match the content.

**Screenshots**
Starting point:
![image](https://user-images.githubusercontent.com/36402974/100222258-f3040600-2f6d-11eb-988a-76f8e2e4ff7f.png)

After pressing forwards:
![image](https://user-images.githubusercontent.com/36402974/100222315-044d1280-2f6e-11eb-95f7-ddfce8a719b2.png)

After fullscreening the browser:
![image](https://user-images.githubusercontent.com/36402974/100222416-2777c200-2f6e-11eb-93b9-8f210d21b2e7.png)

**Comment by sag1v** [comment]
Hi thanks.
What version are you using?

**Comment by ChildishhAlbino** [comment]
latest

**Comment by sag1v** [comment]
Are you using breakpoints? Can you create a small sandbox example please?

**Comment by ChildishhAlbino** [comment]
Yes, I'm using breakpoints. Not familiar with code sandbox and a little busy at the moment so will get back to it. If you can try to resolve it without one that would be helpful. Won't have time before the weekend-ish.

**Comment by sag1v** [comment]
@ChildishhAlbino Can you test if it fixed with the `@next` version?
You can install `react-elastic-carousel@next`

**Comment by ChildishhAlbino** [comment]
Sure thing @sag1v. Will give it a try tomorrow after work and get back to you :D

**Comment by ChildishhAlbino** [comment]
The issue seems to be resolved :D I am experiencing one follow up an issue I'm not sure is related. The pagination dots at the bottom are not always correct.

e.g. I have 4 items in the list and showing 2 per page (incrementing 1 item per click) that should be 3 pagination dots I believe. Not a major issue but still minor inconsistency. Happy to raise a separate issue for it.

**Comment by sag1v** [comment]
Hi, Why 3 pages? If you got 4 items and showing 2 per page, that means 2 pages.

**Comment by ChildishhAlbino** [comment]
Because for me, a page is how many unique sets of items I show. 
For example:

Starting state is Item 1 and 2.
I click next once, now I see Item 2 and 3.
I click next once more, this is Item 3 and 4.

For me, that is three pages, not a major issue but just seems very inconsistent. Just thought I would ensure that is expected behaviour.

**Comment by ChildishhAlbino** [comment]
Not a major issue so happy for you to close this issue!

**Comment by sag1v** [comment]
Yeah i understand what you saying, but with this logic and case that means number of pages will always be number of items - 1.

For 4 items we will have 3 pages
for 10 items we will have 9 pages
for 100 items we will have 99 pages.

I think this defeats the purpose of paging.

If you feel we need to revisit this idea feel free to open a separate issue and we will discuss there :)

I will close this issue when i will merge next to master and release it under latest tag.

**Comment by sag1v** [comment]
available as of version v `0.10.0`
