### ISSUE TITLE
Pagination dots are ellipses instead of circles on iPhone device

### ISSUE THREAD

**Issue by tomaszzmudzinski** [sag1v/react-elastic-carousel#124]
**Describe the bug**
Carousel pagination dots are ellipses instead of circles on iPhone devices.

**To Reproduce**
My colleague checked this on his iPhone 12 Max and I see the same on the iPhone emulator in Xcode. This problem exists even on official examples: https://sag1v.github.io/react-elastic-carousel/

**Expected behavior**
Dots should be always circles, not ellipses.

**Sandbox link**
Sandbox link is not needed, because this problem exists even on official examples. Just take the iPhone or use the Xcode iPhone simulator to check this.

**Screenshots**
<img width="421" alt="Carousel Style Problem" src="https://user-images.githubusercontent.com/4519335/100671190-56bc7380-3360-11eb-8faa-60be307b13b3.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 14.2
 - Browser: Safari
 - Version: Latest

**Comment by sag1v** [comment]
Thanks @tomaszzmudzinski . I don't have an iPhone, i did check in safari (macbook) and there was no issue.
Not sure i know about a goos simulator for iPhone, how can i test this with xcode? 
Is there a way for you to inspect and change CSS to test something? 

I think the problem is that the elements needs:

```css
box-sizing: border-box;
padding: 0;
```

Not sure if both are required or only one of them. But i can't test this currently.

**Comment by tomaszzmudzinski** [comment]
@sag1v could you tell me how to add those styles into proper element? I will check it on iphone simulator (on xCode) and real device and will tell you which line fix issue.

**Comment by sag1v** [comment]
@tomaszzmudzinski Great thanks!
Can you check if it works with `box-sizing: border-box` **instead** of padding?

**Comment by tomaszzmudzinski** [comment]
@sag1v 'box-sizing: border-box' didn't fix thise problem, only padding: 0;

**Comment by sag1v** [comment]
Ok thanks. I will add it to the source code.

**Comment by sag1v** [comment]
available as of version v `0.10.0`
