### ISSUE TITLE
Sensivity of pagination for mobile devices

### ISSUE THREAD

**Issue by tomaszzmudzinski** [sag1v/react-elastic-carousel#127]
**Is your feature request related to a problem? Please describe.**
I am wondering is it possible to slightly change the sensivity for changing pagination page on mobile devices? For me it should be a bit easier to change to the other page.

**Describe the solution you'd like**
The are two ways - give users way to change boundaries for page change or fix that in main library.

**Comment by sag1v** [comment]
Hi, what do you mean?

**Comment by tomaszzmudzinski** [comment]
@sag1v Hmm... how to explain this - now it's little bit hard to swipe between pages on mobile devices (you need to be really accurate to do this). Take a look on phone how your carousel works and how carousel swiping works on https://resume.io. 
You will notice the difference ;)

**Comment by sag1v** [comment]
Interesting, I actually find it harder to swipe in that website you attached. It doesn't always pick up my swipe gestures.
I'm using galaxy S8+ with chrome. 

Not sure exactly what problems you are facing, what do you mean by "you need to be really accurate to do this..."?
