### ISSUE TITLE
Pagination Dots Disappear when resizing window. 

### ISSUE THREAD

**Issue by ChildishhAlbino** [sag1v/react-elastic-carousel#128]
**Describe the bug**
When resizing the window over a breakpoint, if the selected carousel page is greater than the number of total pages after the carousel resizes, the carousel displays empty pagination dots until you press the arrows.

**To Reproduce**
1. Create a carousel with 4 items showing 1 items at a given width, and 2 or more items at a width greater than that.
2. Start with the window-sized such that the carousel shows 4 pagination dots.
3. Select the 3rd page and increase the window size such that you cross your breakpoint.
4. You should now see no highlighted pagination dots.   

**Expected behavior**
In this scenario, the dot furthest to the right after resizing should be highlighted.

**Screenshots**:
Before resizing the window
![image](https://user-images.githubusercontent.com/36402974/101466082-d5cf2e80-3994-11eb-99b6-b16b94a4af5c.png)

After resizing the window
![image](https://user-images.githubusercontent.com/36402974/101466125-e2ec1d80-3994-11eb-9495-84f3860ef182.png)

**Comment by sag1v** [comment]
Hi @ChildishhAlbino Can you check this issue after installing `react-elastic-carousel@next`?

**Comment by ChildishhAlbino** [comment]
Sure thing. Will do after work.

**Comment by ChildishhAlbino** [comment]
Tested and resolved :D

**Comment by sag1v** [comment]
Great. Im keeping it open until i merge it to master and publish it as latest release.

**Comment by sag1v** [comment]
available as of version v `0.10.0`
