### ISSUE TITLE
Make arrow disable params available from Carousel Reference.

### ISSUE THREAD

**Issue by ChildishhAlbino** [sag1v/react-elastic-carousel#129]
**Is your feature request related to a problem? Please describe.**
Looking to build my own navigation component to fit in with my design but frustrated I cannot leverage the `disableOnEnd` functionality through current means.

**Describe the solution you'd like**
Through the Carousel Reference, having access to a property that would say whether or not a particular arrow was disabled or not so I could use this in my own components.

**Describe alternatives you've considered**
* Tracking this myself, was not a good idea.
* Looked into the carousel ref but could not see any values I could use to solve this issue.

**Comment by sag1v** [comment]
Hi, doesn't [renderArrow](https://sag1v.github.io/react-elastic-carousel/renderArrow) prop solve this issue for you? The docs example uses the `isEdge` parameter

**Comment by ChildishhAlbino** [comment]
Hey.

This would work if I had complete control over the positioning and styling, but I want my arrows to be rendered completely outside of the function.
Would be good if I could just say `ref.prevDisabled()` or `ref.nextDisabled()` and have them return booleans for if that arrow should be disabled or not. 

Again not a super high priority just a request if it's not majorly difficult.

**Comment by sag1v** [comment]
Yeah currently there is no idiomatic way to get this info outside the carousel context. 
I usually against ref abusing, i will try to think of an alternative.
