### ISSUE TITLE
Carousel items render in odd fashion when Gatsby App is compiled.

### ISSUE THREAD

**Issue by ChildishhAlbino** [sag1v/react-elastic-carousel#130]
**Describe the bug**
When running with `Gatsby develop` everything works reasonably well, however, when the site is built and run with `gatsby serve` or on Netlify, the carousel slider component renders small for the first frame or so and then adjusts. Unsure how to solve this.

Check it out at: https://emily-kardum.netlify.app/

**To Reproduce**
1. clone ChildishhAlbino/emilykardumDOTcom
2. `npm install`
3. `gatsby develop` in one terminal
4. `gatsby build ; gatsby serve` in another
5. refresh the page of both and compare.

**Expected behavior**
They should render identically.

**Additional context**
Have tested:
* Browsers:
   * Chrome (desktop and mobile)
   * Firefox
   * Safari (mobile)
* Removing CSS:
   * My personal CSS classes.
   * CSS I wrote on carousel component classes.

**Comment by sag1v** [comment]
Thanks @ChildishhAlbino. I'm not sure why this happens, my guess its related to server side rendering and probably `styled-components`. 
I will need to investigate this one.

**Comment by ChildishhAlbino** [comment]
No worries. Let me know if you need any more info from me.

**Comment by ChildishhAlbino** [comment]
Hey mate! Happy holiday! 

Think I found the cause of this one. Needed to install `gatsby-plugin-styled-components` and add it to my config. Works a treat now.

**Comment by sag1v** [comment]
That's great! Thank you 🙂
