### ISSUE TITLE
Border on focus Item.

### ISSUE THREAD

**Issue by Fahad67** [sag1v/react-elastic-carousel#139]
**Is your feature request related to a problem? Please describe.**
I have notice that when click on a item there is a black border or outline appear outside item and orange on mobile phone device. I have tried different ways to remove but nothing work for me. So, Kindly can you provide additional prop or anything by which it will be use choice to show outline or not.

**Solution**
I have resolve that issue by applying this css:
.rec-item-wrapper div {
  outline: none !important;
}

**Additional context**
I think it's better if you can provide any additional props which will use for that to show or hide outline.
![image](https://user-images.githubusercontent.com/75368974/103505179-7113d080-4e7b-11eb-9a3f-11693097d2fb.png)

**Comment by sag1v** [comment]
@Fahad67 
This outline is browser's default, its up to you to decide how to customize and style the elements. 
As for your solution, you are basically styling your own element.

```css
.rec-item-wrapper div {
  outline: none !important;
}
```

Is basically targeting your own `div` and not the carousel, `.rec-item-wrapper` is the wrapper element around the element you passed to the carousel.

**Comment by sag1v** [comment]
I'm closing this. If you still think there is an issue, feel free to reopen
