### ISSUE TITLE
Breakpoints not working correctly

### ISSUE THREAD

**Issue by Luisdv93** [sag1v/react-elastic-carousel#144]
**Describe the bug**
I'm using the breakpoints to set how many items to show like this:
`breakPoints={[
        { width: 1, itemsToShow: 1, itemsToScroll: 1 },
        { width: 1100, itemsToShow: 2, itemsToScroll: 1 }
      ]}`

The breakpoints seem to work at different widths that the ones I set it to, even when I checked the documentation the [breakpoints example](https://sag1v.github.io/react-elastic-carousel/breakPoints) seems to be working incorrectly as well. In the example the carousel should show 2 items once it reaches a width of 550px but it's only showing the items at 776px

**To Reproduce**
1. Set the breakPoints prop on the Carousel component. Ex: Show 2 items at width 550px
2. Resize your window to 550px
3. The carousel doesn't show the correct number of items consistently

**Expected behavior**

**Sandbox link**
https://sag1v.github.io/react-elastic-carousel/breakPoints

**Screenshots**
![image](https://user-images.githubusercontent.com/7731089/104246100-c59aeb00-543b-11eb-9c7b-2a1cbf0ccef0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 87

**Comment by sag1v** [comment]
Hi @Luisdv93 thanks.
The width being watch is not the window but the wrapping element.

**Comment by matheusgprlima** [comment]
I had the same issue and @sag1v if you set any width the breakpoints doesn't change

**Comment by sag1v** [comment]
@matheusgprlima an example would help

**Comment by matheusgprlima** [comment]
**Describe the bug**
@sag1v I'm using the breakpoints to set how many items to show like this:
breakPoints={[{ width: 500, itemsToShow: 1, itemsToScroll: 1 } ]}
![breakpoint_code_example](https://user-images.githubusercontent.com/43975665/104920350-66c2fd80-5976-11eb-9923-27be9bec1378.PNG)
The breakpoints doesn't seem to work as expected. If I set a breakpoint's width to 500px they will work but when I resize the page to a resolution higher than 500px the configuration doesn't come back to the orginal set, in my case it's 4 slides to show. 

**The Original without breakpoints:**     
![slide](https://user-images.githubusercontent.com/43975665/104922625-b8b95280-5979-11eb-8e29-ed84bef60f58.png)

**With breakpoint:**
![BreakPoint_Error](https://user-images.githubusercontent.com/43975665/104922692-cff84000-5979-11eb-91c5-1e61a0e81210.png)

as you can see they are at the same resolution but when there is breakpoint the configuration doesn't change back to the original set of slides.

**Comment by sag1v** [comment]
@matheusgprlima You are missing a breakpoint for `1`. 

The breakpoints are working from the number you provide and upwards. Meaning you provided a breakpoint for `500` and above, but not below

**Comment by matheusgprlima** [comment]
@sag1v Thanks for the wuick response. I've just tried this:
![breakpoint_test](https://user-images.githubusercontent.com/43975665/104925155-36cb2880-597d-11eb-9c0f-611048d66576.PNG)
and got the same result:
![BreakPoint_Error](https://user-images.githubusercontent.com/43975665/104925189-434f8100-597d-11eb-8928-0c9aa87c05d2.png)
Isn't changing

**Comment by sag1v** [comment]
The second breakpoint is set to 1240. Is your container larger than 1240?

**Comment by sag1v** [comment]
Your second breakpoint is set to 1240.
When the container will be larger you will get 4 items

**Comment by matheusgprlima** [comment]
@sag1v thanks a lot dude, great support! I've understood now and now its all set correctly

**Comment by sag1v** [comment]
I'm closing this. If you still think there is an issue, feel free to reopen
