### ISSUE TITLE
outerSpacing option causes - Error: Minified React error #185;

### ISSUE THREAD

**Issue by RundaScath** [sag1v/react-elastic-carousel#146]
When trying to change the default value of the `outerSpacing` option a react error https://reactjs.org/docs/error-decoder.html/?invariant=185 is triggered.  It does not matter what number you change it to.  If it is not 0 the error appears.  You can even see it in your examples section https://sag1v.github.io/react-elastic-carousel/outerSpacing

**Comment by sag1v** [comment]
@RundaScath Thanks. I will check it out

**Comment by sag1v** [comment]
@RundaScath Fixed as of version `0.11.1`
