### ISSUE TITLE
Issue with text bunching up on left side of screen on page load

### ISSUE THREAD

**Issue by allan-glasier** [sag1v/react-elastic-carousel#147]
I'm not sure if this is a bug or I'm just not setting this up right. 

I'm using this with Gatsby and when I load a page for a second the text in the carousel is bunched up on the left side of the screen and then goes to the middle of the screen and runs as it should. 

Any guidance on how I can prevent this from happening when the page is loaded is greatly appreciated.

This is what it looks like with my code underneath:

![image](https://user-images.githubusercontent.com/30414860/105931593-7519b500-6019-11eb-8dc3-fff4010bb524.png)

```javascript
 const carouselItems = [
    { id: 1, text: "2,700 weddings and counting" },
    { id: 2, text: "100% word of mouth" },
    { id: 3, text: "Experience the best in wedding entertainment" },
  ]

<Carousel
  itemsToShow={1}
  easing={"ease"}
  enableAutoPlay={true}
  autoPlaySpeed={2000}
>
  {carouselItems.map(item => (
    <h3 key={item.id}>{item.text}</h3>
  ))}
</Carousel>
```

**Comment by sag1v** [comment]
Hi @allan-glasier Try this solution 
https://github.com/sag1v/react-elastic-carousel/issues/130#issuecomment-749340515

**Comment by allan-glasier** [comment]
That did it! Thank you so much!
