### ISSUE TITLE
Spacing when scroll buttons hide

### ISSUE THREAD

**Issue by nate456789** [sag1v/react-elastic-carousel#148]
I must be missing something on configuring the carousel. When I get to the beginning of the list and the arrow left button hides there is still a gap the width of the button. I would think the first card would align to the left when the button is not visible.
Is there a way to fix this?
Thanks

<img width="1218" alt="carousel gap" src="https://user-images.githubusercontent.com/5215840/106056522-c62eb500-60bc-11eb-9946-b44ba3b96cd7.png">

**Comment by sag1v** [comment]
@nate456789 How is your config looks like, what do you use to hide the button?

**Comment by nate456789** [comment]
I took everything from the example code in your docs to hide the disabled buttons.
Is there a better way to do it?
Thanks

`/* hide disabled buttons */
.rec.rec-arrow:disabled {
    visibility: hidden;
    background-color: #ffffff;
}`




[carousel.txt](https://github.com/sag1v/react-elastic-carousel/files/5888285/carousel.txt)

**Comment by sag1v** [comment]
Got it. Well thats how css works, visibility:hidden will keep that space. You can use display:none if you dont want to keep the space

**Comment by nate456789** [comment]
Thank you that worked. 
I appreciate the fast response.
