### ISSUE TITLE
How can I add outerSpacing manually in my css?

### ISSUE THREAD

**Issue by JudeTejada** [sag1v/react-elastic-carousel#150]
**Describe the bug**
For some reason the outerSpacing isn't working on my nextjs app, and surprisngly I tried it on a fresh nextjs in codesandbox it works well . The main concern is that when I add outerSpacing it crashes my whole app and I'm finding another way to add outerSpacing using manual css

**To Reproduce**
I have no exact idea on how to reproduce the error but If i try to add outerSpacing on my Carousel component it triggers an error of

`Maximum update depth exceeded. this can happen when a component repeatedly calls setState inside conentWillUpdate or componentDidUpdate. React limits the number of nested update to prevent infinite loops.`
```
 <Carousel
        breakPoints={breakpoints}
        itemPadding={[0, 20]}
        itemsToShow={5}
         outerSpacing={100}
   
      >
        <FreelancerCard />
        <FreelancerCard />
        <FreelancerCard />
        <FreelancerCard />
        <FreelancerCard />
        <FreelancerCard />
        <FreelancerCard />
        <FreelancerCard />
        <FreelancerCard />
        <FreelancerCard />
      </Carousel>
````

**Expected behavior**
ReactJS: Maximum update depth exceeded error

**Sandbox link**
Please provide a link to a [codesandbox](https://codesandbox.io/) with the reproduced bug

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Win 10]
 - Browser: Firefox

**Comment by sag1v** [comment]
Hi @JudeTejada This is fixed in latest version.

See #146 for more info
https://github.com/sag1v/react-elastic-carousel/issues/146

**Comment by JudeTejada** [comment]
Thanks!
