### ISSUE TITLE
Feature request: implement variableWidth property

### ISSUE THREAD

**Issue by Bahar101** [sag1v/react-elastic-carousel#152]
I am using carousel slider in multi component and i need this slider to automatically display the right number of items on the screen based on the width of them (for example more than two (<3) items in the carousel) and this is very similar to variableWidth feature in react-slick for displaying, as shown in the image below:
![slider](https://user-images.githubusercontent.com/59749364/108135842-ae1fd500-706d-11eb-97a4-19e1d3db9ceb.png)

**Comment by sag1v** [comment]
Can you explain in more details what exactly do you expect the Carousel to do?

**Comment by Bahar101** [comment]
I need this slider to automatically put the required number of items on the page, based on the width of each items (and the amount of margin provided for them),especially in cases where the size of the items in a batch is not equal.
something like "variableWidth" in react-slick
