### ISSUE TITLE
full screen carousel

### ISSUE THREAD

**Issue by Besuf** [sag1v/react-elastic-carousel#153]
I can't make the carousel full screen there's a slight margin on left and right. i.e I cant have 100vw carousel I rather get 98vw carousel or something like that. the behavior is the same in your code sandbox examples as well. can you describe the reason and how to handle this issue. wonderful library bye the way. Thanks!

**Comment by sag1v** [comment]
Hi, the only margin that react-elastic-carousel has is coming from the `rec-slider-container` element.

So you can just have this rule in your page and it should be ok:

```css
.rec-slider-container {
    margin: 0;
}
```

Also note that `body` has a default `8px` margin by default (at least in chrome).
Also note that in the codesandbox example the `Item` component has margin as well, but obviously its not related to the library.

**Comment by Besuf** [comment]
Thanks for the response,  the new rule solved the issue only when I have many items to show. However there's still the margin in a single item carousel. I got rid of the margin and next button on sandbox example to illustrate the issue on the image below
![Screenshot from 2021-03-03 15-10-17](https://user-images.githubusercontent.com/45813667/109804227-13112880-7c33-11eb-8e8a-5663a0d13636.png)
![Screenshot from 2021-03-03 15-10-42](https://user-images.githubusercontent.com/45813667/109804243-173d4600-7c33-11eb-9028-1c46ea2b0ad3.png)

**Comment by sag1v** [comment]
As i said, make sure the `body` doesn't have its default margin. Chrome (probably other browsers) has a default margin of `8px`.

Also make sure you remove the margin of the `Item` example component, it has `15px` margin.

**Comment by Besuf** [comment]
I removed the items margin and also made the body margin 0. you can try it yourself, if you don't believe me. the margin occurs when I try to display single item carousel. no margin appears for multiple items as it can be seen in the first screenshot.  That's why I sent the screenshots to avoid any misunderstanding.
Here's the fork for your sandbox project [https://codesandbox.io/s/react-elastic-carousel-forked-xcbd6?file=/src/Item.js](url)

**Comment by sag1v** [comment]
It got override by the styled components
![image](https://user-images.githubusercontent.com/9153149/109818678-eb728e00-7c3b-11eb-8f8f-a901ed869042.png)

A more specific rule should fix that:

```css
.rec.rec-slider-container {
  margin: 0;
}
```

![image](https://user-images.githubusercontent.com/9153149/109818819-165ce200-7c3c-11eb-9136-3bc6e23ec829.png)

**Comment by Besuf** [comment]
Thank you Very much this fixed the problem
