### ISSUE TITLE
Show the items that not on  fixed amount value 

### ISSUE THREAD

**Issue by JudeTejada** [sag1v/react-elastic-carousel#155]
Is it possible that the items that are being shown  on the carousel isn't fixed to  a number that was set?
Currently the way that the carousel  is set up on how many items are being shown is with using this particular code `itemsToShow: 6` 

What happens afterward is that if we don't set any itemsToShow, it will just render all the items not set to the amount that the carousel will only show

This will be the result if it wasn't set to fixed
![image](https://user-images.githubusercontent.com/29864561/109795327-c4bf5200-7c51-11eb-8ffa-9764de14c423.png)

If it's fixed and set with itemsToShow
![image](https://user-images.githubusercontent.com/29864561/109795472-f0423c80-7c51-11eb-9fc4-f50fa39e77f4.png)

**Comment by sag1v** [comment]
@JudeTejada Not sure i understand what you're asking here, you want the carousel to display all items?

**Comment by JudeTejada** [comment]
Yes

Currently here's what going on

Current Implentation
![2021-03-03 21-15-55](https://user-images.githubusercontent.com/29864561/109814334-59817a00-7c69-11eb-8e80-1081bbb11a91.gif)

Mockup Implementation
If you could observe on this, when dragging the items, it creates this crop content on the  page because the items that are being shown are not set to fix
![2021-03-03 21-12-22](https://user-images.githubusercontent.com/29864561/109814362-61411e80-7c69-11eb-9534-8ef14cc3211a.gif)

**Comment by sag1v** [comment]
Thanks. Can you create a [codesandbox](https://codesandbox.io/) with this example?

**Comment by JudeTejada** [comment]
Hey
https://codesandbox.io/s/sharp-gareth-s2gxe?file=/src/App.js

Here's a codesandbox that I created,  It has the same implementation that I had on my project except with the stylings and stuffs,

**Comment by sag1v** [comment]
The sandbox is broken. I think you used a folder instead of a file for the card component

**Comment by JudeTejada** [comment]
Here Please Try again
https://codesandbox.io/s/blazing-bash-374mk?file=/src/FreelanceSlider.js

**Comment by JudeTejada** [comment]
any update?

**Comment by sag1v** [comment]
@JudeTejada I don't see any error, what exactly is this example trying to show?

**Comment by SNikhill** [comment]
@JudeTejada 

I believe that the mockup wants you to make sure that the next card is partially visible, right?
![image](https://user-images.githubusercontent.com/51415616/115531024-ef24a780-a2b1-11eb-9af4-cac800eb72e1.png)


If yes, then, `itemsToShow` prop does support decimals so, instead of saying 6, you could say, `6.3` and it will work.
But, I believe, you will need to make slight adjustments to the gap between the elements.
