### ISSUE TITLE
On Next not being called on swipe

### ISSUE THREAD

**Issue by tomland123** [sag1v/react-elastic-carousel#156]
**Describe the bug**
On next start not being called on swipe, despite a previous issue being closed in 2018:

https://github.com/sag1v/react-elastic-carousel/issues/3

**To Reproduce**
1. Go to https://sag1v.github.io/react-elastic-carousel/onNextStart
2. Try swiping
3. No Alert

**Expected behavior**
Alert Should Happen

**Comment by sag1v** [comment]
@tomland123 That's because it not supposed to get triggered by swiping. 
I think you're looking for `onNextEnd` or `onChange`

**Comment by tomland123** [comment]
Sad. I guess this is a feature only I would want. I will close!
