### ISSUE TITLE
Slider not updating if we change itemsToShow 

### ISSUE THREAD

**Issue by petya-mihovska** [sag1v/react-elastic-carousel#157]
Hi, thank you for the wonderfull carousel that you have created. With the latest update, we have noticed the issue described below.

**Describe the bug**
When we change dinamically itemsToShow, the change is not reflecting immediatly.
We have to change the size of the container, so that the new value to be used.
It looks like the issue is caused by the check introduced in https://github.com/sag1v/react-elastic-carousel/issues/146

**To Reproduce**
1. Load the carousel
2. Change the itemsToShow property dinamically

**Expected behavior**
Number of visible slides should change accordingly

**Comment by sag1v** [comment]
@petya-mihovska Thanks! Fixed as of version `0.11.2`
