### ISSUE TITLE
rec-item-wrapper width coming as 0 when testing component in JSDom

### ISSUE THREAD

**Issue by Rajdeepsingh27** [sag1v/react-elastic-carousel#165]
I'm trying to test some breakpoints related logic in my implementation, basically I'm checking for count of visible items when screen width is changed , but all elements wrapped in "rec-item-wrapper" are having a width of 0, when rendered in JSDom (JSDom body by default has a width of 1024px).
I picked this up from JSDom:

< div class="sc-gsTCUz tXlBS rec rec-item-wrapper" id="0" style="width: 0px; padding: 0px 0px 0px 0px;" >

My code:
it('When CardSize is not null, carousel should render based on card size and screen size', () => {
        const { container } = render(
        < div style={{ width: '50rem' }}>
                    < CarouselWrapper cardSize={12}>
                        {jsonData.map((val) => (
                            < Card key={val.id} name={val.name} objectCount={val.count} />
                        ))}
                    </ CarouselWrapper>
                </ div>
        );
        const visibleItems = container.querySelectorAll(
            '.rec-carousel-item-visible'
        );
        expect(visibleItems).not.toBe(null);
        expect(visibleItems).toHaveLength(2);
        const hiddenItems = container.querySelectorAll('.rec-carousel-item-hidden');
        expect(hiddenItems).not.toBe(null);
        expect(hiddenItems).toHaveLength(0);
    });

Based on cardSize, I'm creating breakpoints and passing them to carousel.
When creating similar dom structure in browser, I can see all the widths are generated properly.

**Comment by sag1v** [comment]
Hmm I guess its a problem with JSDOM? I'm not sure how can we solve this at the Carousel side. If you have any suggestions i'm open to hear
