### ISSUE TITLE
React App

### ISSUE THREAD

**Issue by PedroHBessa** [sag1v/react-elastic-carousel#177]
Hi, 

my react App show me this when i try to render the carousel: 

"./node_modules/react-elastic-carousel/dist/index.es.js
Module not found: Can't resolve 'styled-components' in 'C:\daotraining\daotraining\node_modules\react-elastic-carousel\dist'"

Can you help me? 

thanks!!!

**Comment by sag1v** [comment]
See [this issue](https://github.com/sag1v/react-elastic-carousel/issues/57#issuecomment-654638677)
