### ISSUE TITLE
Align Items in the Center

### ISSUE THREAD

**Issue by oqnunes** [sag1v/react-elastic-carousel#178]
**How do I make all items centrally aligned?**

https://user-images.githubusercontent.com/45077154/115112647-57a41980-9f7e-11eb-894f-46710fecc108.mp4

I didn't find any issue with keywords on the subject. 

Sorry if I missed something.

**Comment by sag1v** [comment]
Hi @oqnunes , You need to provide your items a height. You can check out the example in the playground sandbox:

https://codesandbox.io/s/21o46mkwnr

**Comment by oqnunes** [comment]
Oh yeah, it makes perfect sense!

Thanks for listening, this solved my "problem".
