### ISSUE TITLE
How can I activate keyboard arrows for scrolling?

### ISSUE THREAD

**Issue by violinapopova** [sag1v/react-elastic-carousel#180]
Hello, is there a property I can use to activate the scrolling with the left and right arrows on the keyboard, and not only using the mouse for that?

**Comment by SNikhill** [comment]
@violinapopova 

I am not sure about a direct property but, you could simulate a click on the left button or right button when the Left or Right Arrow key press is detected.

- [Keydown event](https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event)
