### ISSUE TITLE
Missing required attribute isRTL warning

### ISSUE THREAD

**Issue by SNikhill** [sag1v/react-elastic-carousel#181]
**Describe the bug**
When the component is used, a warning stating that **isRTL** prop is required is raised by my IDE even though, the documentation as well as the code, intend the prop to remain optional.

**To Reproduce**
This Warning is raised by my IDE(WebStorm) and maybe go unnoticed by other users depending upon their linter/"checker".

**Expected behaviour**
`isRTL` is an optional prop that defaults to false when no value is provided and hence, IDE should not raise any warning.

**Screenshots**
![image](https://user-images.githubusercontent.com/51415616/115527804-0746f780-a2af-11eb-83a3-0380d66c6799.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux Based Distribution
 - Browser: _Not Applicable_
 - Version: _Not Applicable_

**Additional context**
Upon further search, I found the problem in the source code.
`ReactElasticCarouselProps` Interface's `isRTL` missed the Elvis Operator `?:`.
![image](https://user-images.githubusercontent.com/51415616/115528022-437a5800-a2af-11eb-8253-b34d764319cb.png)

**Comment by vadhe** [comment]
this is helpfully thanks
