### ISSUE TITLE
Can't import {consts} from 'react-elastic-carousel

### ISSUE THREAD

**Issue by EdsonArchela** [sag1v/react-elastic-carousel#183]
Module '"react-elastic-carousel"' has no exported member 'consts'. Did you mean to use 'import consts from "react-elastic-carousel"' instead?ts(2614)

**Comment by SNikhill** [comment]
@EdsonArchela 

May I please have the actual `import` statement that you wrote?

**Comment by strawberrysweet** [comment]
I also have this issue. 
This is how I wrote the `import` statement `import Carousel, { consts } from 'react-elastic-carousel';`

**Comment by limamauricio** [comment]
Same erro here. Version "react-elastic-carousel": "^0.11.5"
