### ISSUE TITLE
Swipe does not work with Image

### ISSUE THREAD

**Issue by surjithctly** [sag1v/react-elastic-carousel#196]
**Describe the bug**
When there is an image in the sider, cannot use mouse to swipe on top of Image to swipe to next slide. It just moves along with mouse. 

**To Reproduce**
1. Go to 'https://codesandbox.io/s/mutable-breeze-yptoe?file=/pages/index.js'
2. Mouse Click on the first image. Try to mouse drag to next slide.

**Expected behavior**
It should swipe to next page

**Sandbox link**
Sandbox link: [codesandbox](https://codesandbox.io/s/mutable-breeze-yptoe?file=/pages/index.js)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by carlafranca** [comment]
Same issue if the item is a link (a tag) or it has a (a tag) inside a "li"

**Comment by munafio** [comment]
@sag1v This issue still not solved yet!
