### ISSUE TITLE
Module Not on Vercel

### ISSUE THREAD

**Issue by patrickkabwe** [sag1v/react-elastic-carousel#197]
Below is the error i get when i try to deploy to vercel
![Screenshot from 2021-06-19 12-07-06](https://user-images.githubusercontent.com/64147010/122638864-fcfe7980-d0f6-11eb-9729-30fcc1ccdff1.png)

**Comment by 3adel-bassiony** [comment]
I fixed this issue by installing styled-components
`yarn add styled-components` `npm i styled-components`
