### ISSUE TITLE
Feature request: Pause autoplay on hover

### ISSUE THREAD

**Issue by djsladi** [sag1v/react-elastic-carousel#198]
It would be nice to have "pauseAutoPlayOnHover" true/false -prop on settings to prevent slide to change when user are hovering on the current slide...

**Comment by SNikhill** [comment]
@djsladi 

If you require this functionality immediately, how about [this hack](https://codesandbox.io/s/react-elastic-carousel-forked-l2tf2) that I use.

Basically, detecting `mouseover` and `mouseout` states and disabling/enabling autoplay.

I hope it helps. :)

**Comment by djsladi** [comment]
> @djsladi
> 
> If you require this functionality immediately, how about [this hack](https://codesandbox.io/s/react-elastic-carousel-forked-l2tf2) that I use.
> 
> Basically, detecting `mouseover` and `mouseout` states and disabling/enabling autoplay.
> 
> I hope it helps. :)

Better late than never, this led me to the right solution, very big thanks! 🥇
