### ISSUE TITLE
Does not use passive listeners to improve scrolling performance. [Lighthouse]

### ISSUE THREAD

**Issue by ilKhr** [sag1v/react-elastic-carousel#199]
Hello. 
Chrome lighthouse indicates showing a warning when using your library

> Does not use passive listeners to improve scrolling performance

> Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance

![image](https://user-images.githubusercontent.com/58560537/125264862-eec60680-e30c-11eb-81e5-c3c1e8646ec2.png)

**Comment by InsOpDe** [comment]
@ilKhr what was the solution?
