### ISSUE TITLE
How to modified arrow and dot

### ISSUE THREAD

**Issue by senapahlevi** [sag1v/react-elastic-carousel#212]
I have been used these carousel but i getting stuck dont know how to change color from default color (purple) and also how to change the size of arrow and dots (change size into small size) 

i have solution maybe add tutorial on the documentation , because its not clear i dont know how to change color background in arrow and dots slider ex: i want change color into green color not default color(purple), change size, also add effect for dots animation when getting swipe

**Comment by lilcode-dev** [comment]
You can style it using CSS by referencing the classes it generates when rendered.

Example: 
**Component Code**
```

import React from 'react'
import Carousel from 'react-elastic-carousel'
import {
    CardImage,
    CardCategorieTitle,
    CardWrapper,
} from '@organisms/Cards/Card.style'
import imageRequire from '@helpers/imageRequire'
import './FilterCategoriesCart.scss'

const FilterCategoriesCart = ({list, active, onClick }) => {
    return (
        <Carousel itemsToShow={4}>
                {list.map((l, idx) => (
                    <CardWrapper
                        gridCol={'1fr'}
                        borderRadius="10px"
                        mouse="pointer"
                        userSelect="none"
                        gridGap="0.3rem"
                        onClick={() => onClick(l)}
                        key={idx}
                        gridMargin="0.7rem 0.4rem"
                        gridMinWidth="7.5rem"
                        gridPadding="0.5rem"
                    >
                        <CardImage size="3rem">
                            <img
                                src={imageRequire('./categories.png').default}
                                alt=""
                            />
                        </CardImage>
                        <CardCategorieTitle
                            justify="center"
                            activeColor={active === l ? 'blue' : 'white'}
                        >
                            <span>{l}</span>
                            <div className="active"></div>
                        </CardCategorieTitle>
                    </CardWrapper>
                ))}
        </Carousel>
    )
}

export default FilterCategoriesCart
```

**Style Code**

```
.rec-dot_active {
    background-color: var(--blue) !important;
    box-shadow: 0 0 1px 3px var(--blue) !important;
}
.rec-dot:focus,
.rec-dot:hover {
    box-shadow: 0 0 1px 3px var(--blue) !important;
}
.rec-dot_active:focus,
.rec-dot_active:hover {
    background-color: var(--blue) !important;
    box-shadow: 0 0 1px 3px var(--blue) !important;
}

.rec-arrow {
    
    background-color: var(--blue) !important;
    transition: all 0.3s ease;
    font-size: 1.1rem !important;
    color: white !important;
    width: 1.7rem !important;
    height: 1.7rem !important;
    min-width: 1.7rem !important;
    line-height: 1.7rem !important;
   
}

.rec-arrow:hover:not(:disabled) {
    transform: scale(1.2);
}
```

**Result:** 

![image](https://user-images.githubusercontent.com/69090574/136785694-9df28ac2-c86b-4c8d-9ba1-9964b5aa938b.png)

**Comment by senapahlevi** [comment]
> You can style it using CSS by referencing the classes it generates when rendered.
> 
> Example: **Component Code**
> 
> ```
> 
> import React from 'react'
> import Carousel from 'react-elastic-carousel'
> import {
>     CardImage,
>     CardCategorieTitle,
>     CardWrapper,
> } from '@organisms/Cards/Card.style'
> import imageRequire from '@helpers/imageRequire'
> import './FilterCategoriesCart.scss'
> 
> const FilterCategoriesCart = ({list, active, onClick }) => {
>     return (
>         <Carousel itemsToShow={4}>
>                 {list.map((l, idx) => (
>                     <CardWrapper
>                         gridCol={'1fr'}
>                         borderRadius="10px"
>                         mouse="pointer"
>                         userSelect="none"
>                         gridGap="0.3rem"
>                         onClick={() => onClick(l)}
>                         key={idx}
>                         gridMargin="0.7rem 0.4rem"
>                         gridMinWidth="7.5rem"
>                         gridPadding="0.5rem"
>                     >
>                         <CardImage size="3rem">
>                             <img
>                                 src={imageRequire('./categories.png').default}
>                                 alt=""
>                             />
>                         </CardImage>
>                         <CardCategorieTitle
>                             justify="center"
>                             activeColor={active === l ? 'blue' : 'white'}
>                         >
>                             <span>{l}</span>
>                             <div className="active"></div>
>                         </CardCategorieTitle>
>                     </CardWrapper>
>                 ))}
>         </Carousel>
>     )
> }
> 
> export default FilterCategoriesCart
> ```
> 
> **Style Code**
> 
> ```
> .rec-dot_active {
>     background-color: var(--blue) !important;
>     box-shadow: 0 0 1px 3px var(--blue) !important;
> }
> .rec-dot:focus,
> .rec-dot:hover {
>     box-shadow: 0 0 1px 3px var(--blue) !important;
> }
> .rec-dot_active:focus,
> .rec-dot_active:hover {
>     background-color: var(--blue) !important;
>     box-shadow: 0 0 1px 3px var(--blue) !important;
> }
> 
> .rec-arrow {
>     
>     background-color: var(--blue) !important;
>     transition: all 0.3s ease;
>     font-size: 1.1rem !important;
>     color: white !important;
>     width: 1.7rem !important;
>     height: 1.7rem !important;
>     min-width: 1.7rem !important;
>     line-height: 1.7rem !important;
>    
> }
> 
> .rec-arrow:hover:not(:disabled) {
>     transform: scale(1.2);
> }
> ```
> 
> **Result:**
> 
> ![image](https://user-images.githubusercontent.com/69090574/136785694-9df28ac2-c86b-4c8d-9ba1-9964b5aa938b.png)

hey thanks but how to change the size of dots and arrow because its to big for me

**Comment by lilcode-dev** [comment]
In the example that I show you, I make that style rule change the size of the arrows, look at the font-size property:

```
.rec-arrow {
    background-color: var(--blue) !important;
    transition: all 0.3s ease;
    font-size: 1.1rem !important;  //this!
    color: white !important;
    width: 1.7rem !important;
    height: 1.7rem !important;
    min-width: 1.7rem !important;
    line-height: 1.7rem !important;
}
```

**Comment by lilcode-dev** [comment]
Example for changing point sizes: 

### Style Code
```
.rec-dot {
    height: 5px !important;
    width: 5px !important;
}
```

### Finally

![image](https://user-images.githubusercontent.com/69090574/137170964-3b0b6728-161c-4e9e-83e6-cc572879ad53.png)

**Comment by senapahlevi** [comment]
> Example for changing point sizes:
> 
> ### Style Code
> ```
> .rec-dot {
>     height: 5px !important;
>     width: 5px !important;
> }
> ```
> 
> ### Finally
> ![image](https://user-images.githubusercontent.com/69090574/137170964-3b0b6728-161c-4e9e-83e6-cc572879ad53.png)

hi I have followed and tried to change height and width small as possible but I have a problem that the width of the dots itself cannot be changed like a small circle and the height success to change to small size , because react-elastic-carousel defaults to a large circle
![example problem](https://user-images.githubusercontent.com/40233146/137947903-c09fd7d7-7b18-4d12-b5a9-7134193d0fe7.PNG)

my goal is to change the small circle like this
![goal](https://user-images.githubusercontent.com/40233146/137948220-a155b015-009e-4ca4-b4fe-3fc2db510734.PNG)
s
