### ISSUE TITLE
No definition for autoTabIndexVisibleItems

### ISSUE THREAD

**Issue by djsladi** [sag1v/react-elastic-carousel#222]
**Describe the bug**
Typescript error is raised when autoTabIndexVisibleItems prop is specified.

**To Reproduce**
Try to add autoTabIndexVisibleItems prop to Carousel element

**Expected behavior**
Carousel should put tabindex=0 to any visible slides without errors

![image](https://user-images.githubusercontent.com/39775012/152316937-f39382a9-922a-4391-96fe-604ea1bfcbf8.png)

**Comment by arthurmmedeiros** [comment]
Just ran into this problem when I tried to use this prop. Has this prop ever been available?
