### ISSUE TITLE
How do I get rid of / update the style "margin: 0 10px;" which is a part of SliderContainer.js

### ISSUE THREAD

**Issue by sanishkr** [sag1v/react-elastic-carousel#23]
First of all, thanks for making this package.
I think I am gonna use it in my production if all features required in my org are fulfilled.

Also, great that you have used styled-components. 

Maybe make it(margin) as a prop or remove it as we can introduce our style in its parent.

**Comment by sag1v** [comment]
Most if not all containers and elements has a public CSS class that exposed to the consumer, so you can override or add any styling you like.
In your case, you can override it via the `.rec-slider-container` class name.
