### ISSUE TITLE
error TS2769: No overload matches this call. TS

### ISSUE THREAD

**Issue by 3adel-bassiony** [sag1v/react-elastic-carousel#232]
**Describe the bug**
I was trying to use the react-elastic-carousel and it was working well until I Updated this package to the latest version "@types/react": "^18.0.9", then I got this error:

error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: ReactElasticCarouselProps | Readonly<ReactElasticCarouselProps>): ReactElasticCarousel', gave the following error.
    Type '{ children: Element[]; itemsToShow: number; itemsToScroll: number; isRTL: boolean; showArrows: false; outerSpacing: number; itemPadding: number[]; pagination: true; breakPoints: ({ width: number; itemsToShow: number; itemsToScroll?: undefined; } | { ...; })[]; focusOnSelect: true; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactElasticCarousel> & Readonly<ReactElasticCarouselProps>'.
      Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactElasticCarousel> & Readonly<ReactElasticCarouselProps>'.
  Overload 2 of 2, '(props: ReactElasticCarouselProps, context: any): ReactElasticCarousel', gave the following error.
    Type '{ children: Element[]; itemsToShow: number; itemsToScroll: number; isRTL: boolean; showArrows: false; outerSpacing: number; itemPadding: number[]; pagination: true; breakPoints: ({ width: number; itemsToShow: number; itemsToScroll?: undefined; } | { ...; })[]; focusOnSelect: true; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactElasticCarousel> & Readonly<ReactElasticCarouselProps>'.
      Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactElasticCarousel> & Readonly<ReactElasticCarouselProps>'.

**Comment by nanthakumaran-s** [comment]
@3adel-bassiony getting the same
Did you get any answers about solving this bug??

**Comment by 3adel-bassiony** [comment]
> @3adel-bassiony getting the same
> Did you get any answers about solving this bug??

@nanthakumaran-s Unfortunately no, I'm still waiting for them to fix this issue.

**Comment by cleones** [comment]
Same error.

**Comment by ArturNicolaiewskyPellicioli** [comment]
Same error :(

**Comment by Cristian-ADSI** [comment]
same error
