### ISSUE TITLE
Support with react 18

### ISSUE THREAD

**Issue by asheesh-hub** [sag1v/react-elastic-carousel#235]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by asheesh-hub** [comment]
This doesn't work with react 18.
peer react@"15 - 17"

**Comment by gian-luca-weston** [comment]
+1 This

**Comment by StefanAmEnde** [comment]
Same problem: react-elastic-carousel is not compatible with react 18. It works totally fine with --force. But this is no permanent solution.

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-elastic-carousel@0.11.5
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR!   peer react@">=16.8.0" from @restart/hooks@0.4.6
npm ERR!   node_modules/@restart/hooks
npm ERR!     @restart/hooks@"^0.4.0" from @restart/ui@1.2.0
npm ERR!     node_modules/@restart/ui
npm ERR!       @restart/ui@"^1.2.0" from react-bootstrap@2.3.0
npm ERR!       node_modules/react-bootstrap
npm ERR!         react-bootstrap@"^2.3.0" from the root project
npm ERR!     @restart/hooks@"^0.4.6" from react-bootstrap@2.3.0
npm ERR!     node_modules/react-bootstrap
npm ERR!       react-bootstrap@"^2.3.0" from the root project
npm ERR!   12 more (@restart/ui, @testing-library/react, prop-types-extra, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"15 - 17" from react-elastic-carousel@0.11.5
npm ERR! node_modules/react-elastic-carousel
npm ERR!   react-elastic-carousel@"^0.11.5" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"15 - 17" from react-elastic-carousel@0.11.5
npm ERR!   node_modules/react-elastic-carousel
npm ERR!     react-elastic-carousel@"^0.11.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\stefa\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\stefa\AppData\Local\npm-cache\_logs\2022-06-04T12_47_18_563Z-debug-0.log`

**Comment by ArturNicolaiewskyPellicioli** [comment]
+1 This

**Comment by lkowalczyk87** [comment]
+1

**Comment by Mayank1403** [comment]
+1

**Comment by itseasy21** [comment]
I've forked a version of this and added TS/React 18 support: [https://www.npmjs.com/package/@itseasy21/react-elastic-carousel](https://www.npmjs.com/package/@itseasy21/react-elastic-carousel)
Hopefully, this helps :-)

**Comment by jaypee-0** [comment]
@itseasy21 Thanks for the update

**Comment by sl1taz** [comment]
@itseasy21 Thanks my brother! You save my job ;)  🤩

**Comment by SylvainGibert** [comment]
@itseasy21 thx a lot dude !
