### ISSUE TITLE
How do I style the dots at the bottom?

### ISSUE THREAD

**Issue by sanishkr** [sag1v/react-elastic-carousel#24]
I am trying to use renderPagination, but I will have to pass a whole new component.
I only want to change the styles of the dots at the bottom. Any way to do that or can you introduce new props?

**Comment by sag1v** [comment]
Quoting from #23 
> Most if not all containers and elements has a public CSS class that exposed to the consumer, so you can override or add any styling you like.

In this case you can use the `rec-pagination` and `rec-dot` class names.

**Comment by sanishkr** [comment]
Thanks for the response. If I apply styles to those public classes, inline critical css will not be generated for it which is an important requirement for my project.

For styled-components declared css, critcal css is automatically generated.
For now, I am trying a different approach for both issues #23 and #22

**Comment by sag1v** [comment]
Not sure i understand your issue, can you post an example in [codesandbox](https://codesandbox.io)?

**Comment by ec2ainun** [comment]
any update? @sag1v 
https://sag1v.github.io/react-elastic-carousel/renderPagination
perhaps, you can give an example, how Square component styled

**Comment by sag1v** [comment]
> any update? @sag1v 
> https://sag1v.github.io/react-elastic-carousel/renderPagination
> perhaps, you can give an example, how Square component styled

Its just a component, you can render anything and style it as you wish.

**Comment by ec2ainun** [comment]
> > any update? @sag1v
> > https://sag1v.github.io/react-elastic-carousel/renderPagination
> > perhaps, you can give an example, how Square component styled
> 
> Its just a component, you can render anything and style it as you wish.

yeah i know, but i don't know how to style the dots at the bottom while its inactive or active
that why, detailed how to customized the dot at the bottom or provided Square styled component example, will make it clear for to implement custom style

**Comment by sag1v** [comment]
You can use the classes `.rec-dot` and `.rec-dot_active` to change the style of the dots:

```
.rec-dot {
    background: #ff4343;
    border: 2px #333 solid;
    border-radius: 0;
}
.rec-dot_active {
    background: #59fd59;
}
```

**Comment by ec2ainun** [comment]
thanks its work! @sag1v 
but is it possible implementing it using styled component instead?

**Comment by sag1v** [comment]
@ec2ainun When you use `styled-components`  you are not passing a class name but creating the actual component. 

The[ example of renderPagination in the docs](https://sag1v.github.io/react-elastic-carousel/renderPagination) show this exact case. In [this example](https://raw.githubusercontent.com/sag1v/react-elastic-carousel/master/src/docs/mdx/renderPagination.mdx) the [Square component](https://github.com/sag1v/react-elastic-carousel/blob/master/src/docs/components/Square.js) is created using `styled-components`.
