### ISSUE TITLE
Typescript Error, but Carousel is working on browser

### ISSUE THREAD

**Issue by igorovisk** [sag1v/react-elastic-carousel#243]
I am implementing a react/typescript/windtail project and wanted to use react-elastic-carousel.
Typescript is giving me an error message about types, as you can see on the screenshots uploaded.

Current node version: 16.0

**Dependencies information:**

```
  "phosphor-react": "^1.4.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "styled-components": "^5.3.6"
```

**Development dependencies:**
```
    "@types/react": "^18.0.17",
    "@types/react-dom": "^18.0.6",
    "@vitejs/plugin-react": "^2.1.0",
    "autoprefixer": "^10.4.10",
    "postcss": "^8.4.16",
    "react-elastic-carousel": "^0.11.5",
    "tailwindcss": "^3.1.8",
    "typescript": "^4.6.4",
    "vite": "^3.1.0"
```

**TsConfig Information:** 

```
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

**Sandbox link**
Could not reproduce on sandbox.

**Screenshots**

<img width="881" alt="Screen Shot 2022-09-29 at 10 31 42" src="https://user-images.githubusercontent.com/79643684/193048212-34170256-95b5-4bab-9b8b-a9566299767b.png">

<img width="474" alt="Screen Shot 2022-09-29 at 10 34 47" src="https://user-images.githubusercontent.com/79643684/193048180-c8052d42-bba6-47b7-9227-95886d280523.png">

**Desktop (please complete the following information):**
 - Device: Macbook Air M1 2020
 - OS: MacOs Monterey 12.6
 - Browser Google Chrome

**Comment by wexire** [comment]
Same error

**Comment by ttc-kevin** [comment]
> I am implementing a react/typescript/windtail project and wanted to use react-elastic-carousel. Typescript is giving me an error message about types, as you can see on the screenshots uploaded.
> 
> Current node version: 16.0
> 
> **Dependencies information:**
> 
> ```
>   "phosphor-react": "^1.4.1",
>     "react": "^18.2.0",
>     "react-dom": "^18.2.0",
>     "styled-components": "^5.3.6"
> ```
> 
> **Development dependencies:**
> 
> ```
>     "@types/react": "^18.0.17",
>     "@types/react-dom": "^18.0.6",
>     "@vitejs/plugin-react": "^2.1.0",
>     "autoprefixer": "^10.4.10",
>     "postcss": "^8.4.16",
>     "react-elastic-carousel": "^0.11.5",
>     "tailwindcss": "^3.1.8",
>     "typescript": "^4.6.4",
>     "vite": "^3.1.0"
> ```
> 
> **TsConfig Information:**
> 
> ```
> {
>   "compilerOptions": {
>     "target": "ESNext",
>     "useDefineForClassFields": true,
>     "lib": ["DOM", "DOM.Iterable", "ESNext"],
>     "allowJs": false,
>     "skipLibCheck": true,
>     "esModuleInterop": false,
>     "allowSyntheticDefaultImports": true,
>     "strict": true,
>     "forceConsistentCasingInFileNames": true,
>     "module": "ESNext",
>     "moduleResolution": "Node",
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "noEmit": true,
>     "jsx": "react-jsx"
>   },
>   "include": ["src"],
>   "references": [{ "path": "./tsconfig.node.json" }]
> }
> ```
> 
> **Sandbox link** Could not reproduce on sandbox.
> 
> **Screenshots**
> 
> <img alt="Screen Shot 2022-09-29 at 10 31 42" width="881" src="https://user-images.githubusercontent.com/79643684/193048212-34170256-95b5-4bab-9b8b-a9566299767b.png">
> 
> <img alt="Screen Shot 2022-09-29 at 10 34 47" width="474" src="https://user-images.githubusercontent.com/79643684/193048180-c8052d42-bba6-47b7-9227-95886d280523.png">
> 
> **Desktop (please complete the following information):**
> 
> * Device: Macbook Air M1 2020
> * OS: MacOs Monterey 12.6
> * Browser Google Chrome

I got the same error, and my colleague, [@kgajera](https://github.com/kgajera), helped me come up with a quick (but hacky) solution.
We extended this component as follows:

```jsx
const CustomCarousel = forwardRef<
  any,
  ReactElasticCarouselProps & { children: ReactNode[] }
>((props, ref) => <Carousel ref={ref} {...props} />);
```

Now you can replace your implementation of `<Carousel />` with `<CustomCarousel />` and pass the same props to it as you would with `<Carousel />`.

Hope this helps 🙏

**Comment by igorovisk** [comment]
> > I am implementing a react/typescript/windtail project and wanted to use react-elastic-carousel. Typescript is giving me an error message about types, as you can see on the screenshots uploaded.
> > Current node version: 16.0
> > **Dependencies information:**
> > ```
> >   "phosphor-react": "^1.4.1",
> >     "react": "^18.2.0",
> >     "react-dom": "^18.2.0",
> >     "styled-components": "^5.3.6"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Development dependencies:**
> > ```
> >     "@types/react": "^18.0.17",
> >     "@types/react-dom": "^18.0.6",
> >     "@vitejs/plugin-react": "^2.1.0",
> >     "autoprefixer": "^10.4.10",
> >     "postcss": "^8.4.16",
> >     "react-elastic-carousel": "^0.11.5",
> >     "tailwindcss": "^3.1.8",
> >     "typescript": "^4.6.4",
> >     "vite": "^3.1.0"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **TsConfig Information:**
> > ```
> > {
> >   "compilerOptions": {
> >     "target": "ESNext",
> >     "useDefineForClassFields": true,
> >     "lib": ["DOM", "DOM.Iterable", "ESNext"],
> >     "allowJs": false,
> >     "skipLibCheck": true,
> >     "esModuleInterop": false,
> >     "allowSyntheticDefaultImports": true,
> >     "strict": true,
> >     "forceConsistentCasingInFileNames": true,
> >     "module": "ESNext",
> >     "moduleResolution": "Node",
> >     "resolveJsonModule": true,
> >     "isolatedModules": true,
> >     "noEmit": true,
> >     "jsx": "react-jsx"
> >   },
> >   "include": ["src"],
> >   "references": [{ "path": "./tsconfig.node.json" }]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Sandbox link** Could not reproduce on sandbox.
> > **Screenshots**
> > <img alt="Screen Shot 2022-09-29 at 10 31 42" width="881" src="https://user-images.githubusercontent.com/79643684/193048212-34170256-95b5-4bab-9b8b-a9566299767b.png">
> > <img alt="Screen Shot 2022-09-29 at 10 34 47" width="474" src="https://user-images.githubusercontent.com/79643684/193048180-c8052d42-bba6-47b7-9227-95886d280523.png">
> > **Desktop (please complete the following information):**
> > 
> > * Device: Macbook Air M1 2020
> > * OS: MacOs Monterey 12.6
> > * Browser Google Chrome
> 
> I got the same error, and my colleague and I came up with a quick (but hacky) solution. We extended this component as follows:
> 
> ```js
> const CustomCarousel = forwardRef<
>   any,
>   ReactElasticCarouselProps & { children: ReactNode[] }
> >((props, ref) => <Carousel ref={ref} {...props} />);
> ```
> 
> Now you can replace your implementation of `<Carousel />` with `<CustomCarousel />` and pass the same props to it as you would with `<Carousel />`.
> 
> Hope this helps 🙏

Thanks bro!

**Comment by riungemaina** [comment]
> > I am implementing a react/typescript/windtail project and wanted to use react-elastic-carousel. Typescript is giving me an error message about types, as you can see on the screenshots uploaded.
> > Current node version: 16.0
> > **Dependencies information:**
> > ```
> >   "phosphor-react": "^1.4.1",
> >     "react": "^18.2.0",
> >     "react-dom": "^18.2.0",
> >     "styled-components": "^5.3.6"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Development dependencies:**
> > ```
> >     "@types/react": "^18.0.17",
> >     "@types/react-dom": "^18.0.6",
> >     "@vitejs/plugin-react": "^2.1.0",
> >     "autoprefixer": "^10.4.10",
> >     "postcss": "^8.4.16",
> >     "react-elastic-carousel": "^0.11.5",
> >     "tailwindcss": "^3.1.8",
> >     "typescript": "^4.6.4",
> >     "vite": "^3.1.0"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **TsConfig Information:**
> > ```
> > {
> >   "compilerOptions": {
> >     "target": "ESNext",
> >     "useDefineForClassFields": true,
> >     "lib": ["DOM", "DOM.Iterable", "ESNext"],
> >     "allowJs": false,
> >     "skipLibCheck": true,
> >     "esModuleInterop": false,
> >     "allowSyntheticDefaultImports": true,
> >     "strict": true,
> >     "forceConsistentCasingInFileNames": true,
> >     "module": "ESNext",
> >     "moduleResolution": "Node",
> >     "resolveJsonModule": true,
> >     "isolatedModules": true,
> >     "noEmit": true,
> >     "jsx": "react-jsx"
> >   },
> >   "include": ["src"],
> >   "references": [{ "path": "./tsconfig.node.json" }]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Sandbox link** Could not reproduce on sandbox.
> > **Screenshots**
> > <img alt="Screen Shot 2022-09-29 at 10 31 42" width="881" src="https://user-images.githubusercontent.com/79643684/193048212-34170256-95b5-4bab-9b8b-a9566299767b.png">
> > <img alt="Screen Shot 2022-09-29 at 10 34 47" width="474" src="https://user-images.githubusercontent.com/79643684/193048180-c8052d42-bba6-47b7-9227-95886d280523.png">
> > **Desktop (please complete the following information):**
> > 
> > * Device: Macbook Air M1 2020
> > * OS: MacOs Monterey 12.6
> > * Browser Google Chrome
> 
> I got the same error, and my colleague, [@kgajera](https://github.com/kgajera), helped me come up with a quick (but hacky) solution. We extended this component as follows:
> 
> ```js
> const CustomCarousel = forwardRef<
>   any,
>   ReactElasticCarouselProps & { children: ReactNode[] }
> >((props, ref) => <Carousel ref={ref} {...props} />);
> ```
> 
> Now you can replace your implementation of `<Carousel />` with `<CustomCarousel />` and pass the same props to it as you would with `<Carousel />`.
> 
> Hope this helps 🙏

Worked for me.
