### ISSUE TITLE
Breakpoints not working properly

### ISSUE THREAD

**Issue by asmath-s** [sag1v/react-elastic-carousel#248]
When I added some breakpoints it was not working properly.

  const breakPoints = [
    { width: 460, itemsToShow: 1 },
    { width: 767, itemsToShow: 2 },
    { width: 991, itemsToShow: 3 },
    { width: 1200, itemsToShow: 5 },
    { width: 1400, itemsToShow: 6 },
    { width: 1920, itemsToShow: 7 },
  ];

these are the breakpoints I added. all size of the screen shows 991 breakpoint items.

      <Carousel
            pagination={false}
            itemPadding={[30, 0]}
            breakPoints={breakPoints}
            renderArrow={myArrow}
          >
          ..........
       <Carousel/>

![image](https://user-images.githubusercontent.com/52459986/204454662-45a3a1fc-212e-48e2-929c-b2fe6adf246a.png)

**Comment by juliojesus15** [comment]
I think your problem is not due to a property fault.  Width does not refer to the width of the viewport.

Use this property to see the current size of the container
onResize={currentBreakPoint => console.log(currentBreakPoint)}

salu2
