### ISSUE TITLE
variableWidth for Slider

### ISSUE THREAD

**Issue by sanishkr** [sag1v/react-elastic-carousel#26]
**Is your feature request related to a problem? Please describe.**
I am trying to display more than one (<2) items in the carousel which is a quite common trend nowadays. This is very similar to [variableWidth](https://react-slick.neostack.com/docs/example/variable-width) feature in react-slick. An example [sandox link](https://codesandbox.io/s/rough-wave-xyg9m?fontsize=14&hidenavigation=1&theme=dark). In react-elastic-carousel's case, either it won't show more than one item at a time or something breaks after reaching the last item in the slider.

**Describe the solution you'd like**
When one item is swiped/slided, the next item should appear exactly in place(position) of prev item.

**Describe alternatives you've considered**
I tried below variations:
1.  setting itemsToScroll=1.2
2. applying style
```
.rec-item-wrapper {
 width: 100% !important;
}
```
3. returning always 1 from getNumOfVisibleItems()
4. setting itemPosition={consts.START}

**Additional context**
I think the function onNextStart or updateSliderPosition needs to be updated for this.

Please let me know if I am missing something or this can be already achieved via current settings and there is no need to make a new feature. 
Here is a [sandox link](https://codesandbox.io/s/black-frog-5zop4?fontsize=14&hidenavigation=1&theme=dark) where I am trying.

**Comment by sag1v** [comment]
@sanishkr This maybe a nice addition, but it kind of breaks the number of items to show.
Even `react-slick` breaks in your example, try giving `slidesToShow` any number above 5 (even 5 is breaking the UI in some way).

I think that this option should only be available with `infinite: true` as you can fill up the track with items. Currently `react-elastic-carousel` does not support `infinite` so there is no point of supporting different width of items.

I do plan to support infinite in the future (and i do have a WIP prototype), but until then this one is a no-go.
