### ISSUE TITLE
Fix for styled-components v5.0.0

### ISSUE THREAD

**Issue by sanishkr** [sag1v/react-elastic-carousel#31]
**Describe the bug**
Breaks for newer version of `styled-components`

**To Reproduce**
1. Go to https://codesandbox.io/s/react-elastic-carousel-fusb6
2. Update styled-components to > 4.4.1, eg: 5.0.0

**Expected behavior**
Should work as it is.

**Additional context**
Even if we update `react` and `react-dom` to latest versions, it gives something like this.
<img width="527" alt="Screenshot 2020-02-12 at 11 51 56 AM" src="https://user-images.githubusercontent.com/13197735/74308385-161e4a00-4d8e-11ea-877a-a2a0d70f74e9.png">

**Comment by sag1v** [comment]
Thanks for pointing that out, this is very helpful! 

`styled-components` changed their API regarding attributes (including `style`).  We will support `styled-components` v5 on next major (with some new features).

Currently we support version 4.x.x as you can see in [package.json](https://github.com/sag1v/react-elastic-carousel/blob/master/package.json#L31)

**Comment by sanishkr** [comment]
When will that release?

**Comment by sanishkr** [comment]
@sag1v  I have sent a PR #32. Can you please check and publish soon, if it's all right.

**Comment by sag1v** [comment]
@sanishkr Thanks for that! but i'm afraid it would introduce a breaking change because `styled-components` is a peer dependency, this means we will need to bump a major version.
I'm working on a new major version and already made this change, i haven't pushed the new WIP branch yet, but hopefully i will have time to do it this week.

This. new branch includes a rewrite with hooks and some new features that were missing like infinite scrolling and lazy loading.

**Comment by sag1v** [comment]
@probablyup Would love get your advice, this package (`react-elastic-carousel`) has a peer dependency of `"styled-components": "^4.0.0"`. The latest version of SC introduced the new `attr` syntax. 

You think it's safe to upgrade to the latest SC version and refactor to the new `attr` syntax without bumping a major for this package (`react-elastic-carousel`)?

**Comment by sanishkr** [comment]
Hi @sag1v ,  Could you please update when you will release next version with upgraded styled-components? It's been quite some time.

**Comment by sag1v** [comment]
Resolved with 8a6d784

**Comment by sanishkr** [comment]
I had to upgrade all the packages in above example, and it works now, thanks @sag1v 

[CodeSandbox link](https://codesandbox.io/s/react-elastic-carousel-8e8dw)

**Comment by sag1v** [comment]
> I had to upgrade all the packages in above example, and it works now, thanks @sag1v 
> 
> [CodeSandbox link](https://codesandbox.io/s/react-elastic-carousel-8e8dw)

NP. I updated the sandbox example, can you check its working without updating any package?

**Comment by sanishkr** [comment]
If you are talking about the [CSB](https://codesandbox.io/s/21o46mkwnr) link in readme of this repo, it works but it's package versions all way too old.

**Comment by sag1v** [comment]
Thanks. Fixes
