### ISSUE TITLE
Infinite

### ISSUE THREAD

**Issue by MehdiAghighi** [sag1v/react-elastic-carousel#33]
can you please add a infinite slider option to the Library?

**Comment by sag1v** [comment]
I'm working on it for the next major version

**Comment by sag1v** [comment]
Unfortunately i didn't have much time to work on it the last couple of months, i will try to do it soon.  
Closing this and will update on progress in #9 .

**Comment by noetic-bajwa** [comment]
When will you add Infinite Loop in the Official Library ?

**Comment by noetic-bajwa** [comment]
> Unfortunately i didn't have much time to work on it the last couple of months, i will try to do it soon.
> Closing this and will update on progress in #9 .

Please give an Update on That

**Comment by Uny1me** [comment]
This is really needed, thank you
