### ISSUE TITLE
Can't resolve 'styled-components' in 'node_modules\react-elastic-carousel\dist'

### ISSUE THREAD

**Issue by NguyenTrungMaxBka** [sag1v/react-elastic-carousel#35]
I imported and run then i got error. Can you give me solution

**Comment by yudican** [comment]
Just run yarn add styled-components in your projects

**Comment by yudican** [comment]
> I imported and run then i got error. Can you give me solution

Just run yarn add styled-components in your projects

**Comment by sag1v** [comment]
@yudican is spot on. 
`styled-components` is peer dependency
