### ISSUE TITLE
Feature request: Disable or hide arrows on first/last pages

### ISSUE THREAD

**Issue by aarowman** [sag1v/react-elastic-carousel#36]
Currently if you are on the first page, the PREV arrow still shows normal. If you click it, it does not change the content.
It would be nice if we had an option to disable the buttons so they are shown as disabled (maybe add separate class styling for these, but that's different), and/or hide the button altogether (possibly with a placeholder).

I was able to implement this manually by editing the renderArrow() function and using the `ref` of the Carousel and checking `ref.current.state.activePage`, and comparing to the total number of pages (`ref.current.state.getNumOfPages()` and offset by 1), but this is far from ideal. Then, I also have to render my own arrow and cannot use the default.

**Comment by sag1v** [comment]
@aarowman Great idea. Not sure what would be the ideal API here as some people will want to disable it, some will want to hide it and some might want to allow it (maybe there are more cases).

I don't want to bloat the component with props (there are too many as it is).
What do you about just adding a class to the button when we reach the end of the slides and the consumer can do whatever he wants via the class, disabled it or hide it etc?

**Comment by aarowman** [comment]
Ideally it would be an optional prop just like `pagination` or `showArrows`. Something like an enum `showEndPageArrows` set to "show", "hide", "disable".
Possibly also just always hide or disable them - I'm not sure why the arrow is needed if you're on the edge page.

The class idea is fine too, because it's more dynamic. Would that allow for disabling the button instead of hiding it?

As an aside, what's wrong with another prop if it's valuable? If your'e concerned about too many props, there are already other ones that may not be needed, e.g. having 4 different props for the onNext/onPrev callbacks - this could be combined into a single one (I'm curious why there is a start and an end, but I'm sure there's a reason). Perhaps an onChange function (see #37) could cover these conditions if you allow a pre/post flag or return callback. 
There's also a few separate props like multiple boolean flags instead of one array that takes more than one (like padding does).

**Comment by sag1v** [comment]
>  I'm not sure why the arrow is needed if you're on the edge page

When i built this component (needed it in my previous job couple of years ago) i had this use case when i needed it to show.

---

>The class idea is fine too, because it's more dynamic. Would that allow for disabling the button instead of hiding it?

Yeah, you can disable a button via styling e.g: `pointer-events: none`

---

>I'm curious why there is a start and an end, but I'm sure there's a reason

Valid question, i have prev and end separated so you can add different logic or just "listen" to one of them, for example you don't care about prev only about next. I could pass the direction as a parameter to the callback, but at that time i decided it's better to have it separated (arguable of course).

We got *Start *End callbacks because i had a use case when i needed to trigger something before and after animation, probably a specific use case for me but i wrote this component for my self at first so this is why we have it today :)  

I understand that the most popular use case would be to get the current index, as this component is un-controlled and one would probably want to sync the current index with the local state.
I'm open for suggestions, and of course for PR's :)

---

>There's also a few separate props like multiple boolean flags instead of one array that takes more than one (like padding does).

Which Booleans can be an array?

**Comment by aarowman** [comment]
@sag1v Thanks for clarifying. 

> Yeah, you can disable a button via styling e.g: pointer-events: none

Apparently that only works for the mouse but isn't quite the same as disabling: https://bitsofco.de/theres-no-reason-to-use-pointer-events-for-html-elements/

> probably a specific use case for me but i wrote this component for my self at first so this is why we have it today :)

Yeah, that makes total sense! I'm sure I would've done the same thing. This is an awesome library now that you've opened it up! Thank you.

> I understand that the most popular use case would be to get the current index, as this component is un-controlled and one would probably want to sync the current index with the local state.

You got it, that's exactly my thought. (As shown in issue #37)

> Which Booleans can be an array?

This is subjective, but maybe something like transition props could be a single object (not just booleans): `transitionMs`, `easing`, `tiltEasing`, `enableTilt`. Another 'group' is swipe/auto play props: `enableSwipe`, `enableMouseSwipe`, `enableAutoPlay`

You could either set them together as a props object or make it an enum like itemPosition was (e.g. swipe could be "touch", "mouse", "all" or something like that). Again, this is subjective - I was just pointing out that there are other ways to reduce the number of props if that was your concern.

**Comment by waynehaffenden** [comment]
@aarowman I would love to do exactly the same as you, have you got an example of your current working code so I can temporarily make mine work until this gets figured out? Cheers

**Comment by sag1v** [comment]
@aarowman @waynehaffenden Theres now a way to disable arrows with the `disableArrowsOnEnd` prop (which is set to `true` by default by the way) :)

Thanks for your contribution 🤗

**Comment by aarowman** [comment]
Awesome, thanks @sag1v !

**Comment by aarowman** [comment]
> 
> 
> @aarowman I would love to do exactly the same as you, have you got an example of your current working code so I can temporarily make mine work until this gets figured out? Cheers

@waynehaffenden It looks like this is covered with the new version now! Let me know if you still want an example

**Comment by waynehaffenden** [comment]
@aarowman thank you for the offer but as you said this is now available in the new version :)
