### ISSUE TITLE
Feature Request: Implement onChange function

### ISSUE THREAD

**Issue by aarowman** [sag1v/react-elastic-carousel#37]
**Is your feature request related to a problem? Please describe.**
It is frustrating when I want to know the current page so I can implement my own logic (e.g. set a state variable)

**Describe the solution you'd like**
Implement an onChange parameter that accepts a callback function, so everytime the page changes (prev/next arrow click, or goTo() is called), then the callback is fired.

**Describe alternatives you've considered**
Manually accessing the ref to get the state: `ref.current.state.xx`, but can only 'trigger' this for renderArrow() or other functions that are called multiple times - cannot see WHEN it was changed naturally.

**Additional context**
N/A

**Comment by JeremiahUL** [comment]
Has this been fixed?

**Comment by sag1v** [comment]
@aarowman 
You got callbacks for start and end changes, isn't that sufficient? 

Start of change callbacks:
[onNextStart](https://sag1v.github.io/react-elastic-carousel/onNextStart) / [onPrevStart](https://sag1v.github.io/react-elastic-carousel/onPrevStart)

End of change callbacks:
[onNextEnd](https://sag1v.github.io/react-elastic-carousel/onNextEnd) / [onPrevEnd](https://sag1v.github.io/react-elastic-carousel/onPrevEnd)

**Comment by JeremiahUL** [comment]
I wanted to trigger a change externally ... maybe I mixed it up, but I am
trying to trigger a swipe but clicking a different button outside the
carousel

**Comment by sag1v** [comment]
Got it. For this you have the [slideNext and slidePrev](https://sag1v.github.io/react-elastic-carousel/slideNext) API, these function are attached to the instance of the component so you will need a `ref` to the carousel and trigger it as you wish.

The example in the docs should set you in the right direction, let me know if there is anything you don't understand :)

**Comment by JeremiahUL** [comment]
Thanks a lot. : )

**Comment by aarowman** [comment]
@sag1v The callbacks are not quite sufficient for a few reasons:
1. If we use goTo(), these aren't triggered
2. Clicking on a pagination button is like goTo() and does not trigger onNext* or onPrev*
3. Having to set up multiple callbacks for the same behavior is undesirable

My situation is trying to use React with hooks (similar to using redux) and changing a local state variable to know the current page. Ultimately the goal was to know if I was on the first or last page (see issue #36), but there are other cases such as wanting to change behavior of an external component beyond this one.

**Comment by sag1v** [comment]
@aarowman 
1. Actually `onNextEnd` and `onPrevEnd` are triggered in this case
2. Actually `onNextEnd` and `onPrevEnd` are triggered in this case
3. You might be right about the names, `onNextEnd` and `onPrevEnd` are like separate `onChange` for both directions and should be triggered after the animation is finished. Maybe i should have called them just `onChange` and pass the direction as a parameter. 

As for your specific use case for tracking the page number, maybe it should be another piece of data that the callbacks should receive?

**Comment by aarowman** [comment]
@sag1v Thanks for the clarification! I didn't realize these were triggered when something changes outside of the actual next/prev clicks. Yes, this seems like they pretty much ARE the onChange function. I like the idea of just calling it onChange and passing the direction (or just the value). Perhaps that could be the solution?

If the page value was passed, that would also be very helpful. Something like onChange as a new function would likely need that. I'd imagine something similar to the [Material UI Tabs API](https://material-ui.com/api/tabs/), regarding active content. It has a `value` prop and an `onChange` function prop. The onChange passes the new index value, which comes from the child.

Note: this is what I have to do currently to determine the page (inside the renderArrow function)
```javascript
activePage = carouselRef.current.state.activePage + 1; //state.activePage is 0-indexed - add 1 so it relates to numOfPages correctly
lastPage = carouselRef.current.getNumOfPages();
```

**Comment by sag1v** [comment]
@aarowman I added the `onChange` callback as you requested. Passing it the current item as well as the current page index. I've done the same to the other on***End callbacks by the way.

Available as of version `0.6.0` :)

https://sag1v.github.io/react-elastic-carousel/onChange

**Comment by aarowman** [comment]
@sag1v  Is there a need for the on***End callbacks if this one exists? Should they be deprecated in a future version in this case?

**Comment by sag1v** [comment]
> @sag1v  Is there a need for the on***End callbacks if this one exists? Should they be deprecated in a future version in this case?
> 
> Maybe consider adding `beforeChange` to replace the on***Start callbacks too

They are not deprecated because some use cases needs a separate callback for next/prev or before/after animation

**Comment by aarowman** [comment]
I see. Yeah that's true since `onChange` does not say which direction it went (prev or next). That could be an alternative solution - adding a 3rd param to the onChange call and removing the "extra" 2 functions.

Consider something like `onChange(currentItem, pageIndex, direction)` and `beforeChange(currentItem, pageIndex, direction)` - each direction would be one of the `consts` like `NEXT` and `PREV`
