### ISSUE TITLE
Hide arrow buttons when not enough content

### ISSUE THREAD

**Issue by waynehaffenden** [sag1v/react-elastic-carousel#46]
It would be great if the arrow buttons were not rendered if there wasn't enough content. An example is that I use this to show news articles in a card, if there is only one article for example, it looks a little silly with disabled arrows either side. So I guess the time the arrows would render is when there is enough items to actually enable the "next" arrow button.

**Comment by sag1v** [comment]
@waynehaffenden The arrow buttons have a public CSS class of `.rec-arrow`, when they are disabled they get the `disabled` attribute, which means you can just write a CSS rule of your own:

For example:
```
.rec-arrow[disabled] {
    visibility: hidden;
}
```

If you want more control, you can create the buttons on your own via the [renderArrow](https://sag1v.github.io/react-elastic-carousel/renderArrow) prop.

Is this sufficient?

**Comment by waynehaffenden** [comment]
@sag1v  This works great, thank you

**Comment by sag1v** [comment]
So basically what you after is that if `itemsToShow` is equal to the `items.length` then do something with the arrows, in your case you want to hide them both.

You can achieve this by either conditionally pass the `showArrows` prop:
```
showArrows={itemsToShow < items.length}
```

Or if you want more fine grained control, you can create your own buttons with the [renderArrow](https://sag1v.github.io/react-elastic-carousel/renderArrow) prop and pass a class or anything via the same logic:
```
function myArrow({ type, onClick, isEdge }) {
  const pointer = type === consts.PREV ? "👈" : "👉";
  return (
    <button
      onClick={onClick}
      disabled={isEdge}
      className={itemsToShow < items.length ? "" : "hide"}
    >
      {pointer}
    </button>
  );
}
```

Is this what you are after?

**Comment by waynehaffenden** [comment]
@sag1v How do I get access to the current itemsToShow based on breakPoints from the component without attempting to work out the window visible size etc?

**Comment by waynehaffenden** [comment]
@sag1v Could it be passed through to renderArrow function as a parameter? The idea is that imagine I had 3 items to show and 3 items, in this case no arrows visible (nothing more to scroll), if I then shrink my browser window and hit tablet screen size, the arrows are now visible as there is 2 items to show (breakpoints) and 3 items (1 to scroll to). Does this make sense?

**Comment by sag1v** [comment]
@waynehaffenden You can hook to the [onResize](https://sag1v.github.io/react-elastic-carousel/onResize) callback to keep track of the current used breakpoint.

**Comment by waynehaffenden** [comment]
@sag1v Thank you for your suggestion, this seems to work, feels like a bit of a hack though. Any chance you could implement this as an optional prop to the Carousel, so if people want this feature (hiding the arrow buttons/bullets) when not enough content (i.e when both arrows are disabled)?
