### ISSUE TITLE
Dynamic height of items doesn't adjust actual carousel height

### ISSUE THREAD

**Issue by waynehaffenden** [sag1v/react-elastic-carousel#47]
I have items within the carousel that change in size based on media queries, this works great for normal use. However, if I resize the desktop browser for example, the height of the original items still remains for the carousel component, even though it's items are much smaller. This leaves a huge blank space of the original height of the items. This seems to only have an effect when the browser is shrunk in size, when stretching it back out this doesn't happen.

**Comment by sag1v** [comment]
Thanks @waynehaffenden , can you please create a minimal example in codesandbox?

**Comment by waynehaffenden** [comment]
@sag1v Hopefully this shows what I mean :) [https://codesandbox.io/s/cool-kalam-vs4ye?file=/src/App.js](https://codesandbox.io/s/cool-kalam-vs4ye?file=/src/App.js)

**Comment by sag1v** [comment]
@waynehaffenden Thanks!
Can you please check if this css rule helps:
```
.rec.rec-slider {
  min-height: auto;
}
```

**Comment by waynehaffenden** [comment]
@sag1v Yes! This fixes the issue, will this be included in your package or is this something I should apply manually to my own projects?

**Comment by sag1v** [comment]
@waynehaffenden I'm not sure it is wise to include in the lib as i think this might break some other views, especially vertical mode. Moreover i didn't encounter your scenario elsewhere, so not sure why exactly you were facing with this bug. Maybe the fact that the height is determined asynchronously after the image was fetched and rendered. 

Anyway, i think for now we will leave it as is, if we see some more people get the same bug we will re-think this over.

**Comment by waynehaffenden** [comment]
@sag1v Makes sense, thank you for looking into this for me, really appreciate it.

**Comment by waynehaffenden** [comment]
@sag1v (Sorry!) Since adding your CSS fix above when resizing the browser window, I get this warning from React:

`react_devtools_backend.js:6 Over 200 classes were generated for component styled.div with the id of "sc-AxhUy".
Consider using the attrs method, together with a style object for frequently changed styles.
Example:
  const Component = styled.div.attrs(props => ({
    style: {
      background: props.background,
    },
  }))`width: 100%;``

Any ideas?

**Comment by sag1v** [comment]
Yeah i think i know where this warning is coming from, [i gave the element a `height` prop](https://github.com/sag1v/react-elastic-carousel/blob/master/src/react-elastic-carousel/components/Carousel.js#L480) which is a valid html attribute for div's. I should re-name it so it wont get passed down to the underline DOM element.

**Comment by sag1v** [comment]
@waynehaffenden the warning should be gone if you upgrade to the latest version `v0.6.4` 🙂

**Comment by waynehaffenden** [comment]
@sag1v Yep, all fixed, great job :)
