### ISSUE TITLE
 Error: Can't resolve 'styled-components'

### ISSUE THREAD

**Issue by SalahAdDin** [sag1v/react-elastic-carousel#48]
**Describe the bug**
After installing and importing this package, the console shows me a missing package.

**To Reproduce**
1. Install the package with `yarn`.
2. Import it into a component
3. Run the project
4. Don't see anything in the site
5. Go to the console to get the error

**Expected behavior**
We must see the whole event with the carousel.

**Screenshots**
![Screen Capture_select-area_20200601133243](https://user-images.githubusercontent.com/5034215/83400946-73f1a300-a40c-11ea-8c34-1816e236fb74.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser Chromium
 - Version 81
**Additional context**

**Comment by sag1v** [comment]
@SalahAdDin Thanks. Note that `styled-components` is a peer dependency of `react-elastic-carousel` and you will need to install it as well.

**Comment by SalahAdDin** [comment]
@sag1v So, you should put it on the documentation, because we don't know it until we get this bug.

**Comment by sag1v** [comment]
@SalahAdDin I understand, though all peer dependencies (including react and react-dom) should be installed by the consumer. 

Where exactly do you think its best to put it in the docs?

**Comment by SalahAdDin** [comment]
In the installing section, as a dependency you can add it in the same line, or make it patent we need to install it, because, at least for me, many libraries, as `material-ui` installs their dependences by itself (`svgr` for instance).

**Comment by sag1v** [comment]
@SalahAdDin Thanks, I added it to the docs.

>because, at least for me, many libraries, as material-ui installs their dependences by itself 

Some dependencies can't be added by 3rd party libraries because you either don't want or can't have duplicate instances of them. With styled-components (or react) for example, its not allowed to have duplicates. When you install a library and not installing a peer dependency of it you should see an error/warning about `unmet peer dependency` in your terminal.

**Comment by irasanchez** [comment]
Could this be added to the Readme as well please for the same reasons? Thank you.

**Comment by sag1v** [comment]
@irasanchez  It is in the [readme](https://github.com/sag1v/react-elastic-carousel#note).

Though i just found out its not updated in NPM :/
I will update it thanks

**Comment by sag1v** [comment]
@irasanchez fixed

**Comment by JonasJW** [comment]
Hey @sag1v, I really like this project but I think it would be better if you wouldn't make styled-components mandatory as it is a dependency I would rather avoid. Why exactly did you chose to use it instead of making it with native react?

**Comment by sag1v** [comment]
> Hey @sag1v, I really like this project but I think it would be better if you wouldn't make styled-components mandatory as it is a dependency I would rather avoid. Why exactly did you chose to use it instead of making it with native react?

Hi, i like styled approach over css files.
It is mandatory because styled-components should be in peerDependencies so no duplication.
May i ask why do you want to avoid installing it?
The alternative would be to ask consumers to include css file instead which i don't like much.

**Comment by JonasJW** [comment]
> May i ask why do you want to avoid installing it?

I might be wrong but to my knowledge styled-components adds a significant size to the bundle size. I have been using Swiper before but it was too large so I'm looking for something lightweight

**Comment by sag1v** [comment]
AFAIK, its ~12kb. not that heavy :)

**Comment by JonasJW** [comment]
> AFAIK, its ~12kb. not that heavy :)

Oh ok then I'm mistaken, sorry.
