### ISSUE TITLE
Feature request: Disable or hide pagination

### ISSUE THREAD

**Issue by SalahAdDin** [sag1v/react-elastic-carousel#49]
Our design requires not showing arrows and paginators.
You already provide a solution to hide arrows, but no any option to hide also padding, and it would be great if you can provide an option for it.

Great work, Thanks!

**Comment by sag1v** [comment]
@SalahAdDin There is a prop for that:
```
pagination={false}
```

If you want more control you can render the pagination yourself with the [renderPagination](https://sag1v.github.io/react-elastic-carousel/renderPagination) prop.

**Comment by SalahAdDin** [comment]
Oh, yes, you are right, my mistake.
