### ISSUE TITLE
Outline around items

### ISSUE THREAD

**Issue by waynehaffenden** [sag1v/react-elastic-carousel#51]
There is an outline around each item within the carousel when clicking on the item, since the latest update.

**Comment by waynehaffenden** [comment]
This is happening on the focus of the .rec-item-wrapper

**Comment by sag1v** [comment]
@waynehaffenden Yeah because they are focusable via `tabindex`.

You can target each child of the `.slider` and disable it, keep in mind that this is not very a11y friendly.

```
.rec-slider [tabindex] {
    outline: none;
}
```

**Comment by waynehaffenden** [comment]
@sag1v That makes sense, completely agree about accessibility, although this way I can change the colour to suit the design better. Thank you
