### ISSUE TITLE
Cannot use goTo to reach last item after appending new items

### ISSUE THREAD

**Issue by waterrhett** [sag1v/react-elastic-carousel#52]
Hi, [sag1v](https://github.com/sag1v). Thanks for the library!

I am trying to dynamically append items to the carousel.
Each time I append a new item, I would like to use `goTo` to display it (the last item).
However, currently this only goes to the second last item.

You can find a minimal example here:
https://codesandbox.io/s/react-elastic-carousel-l9y65?file=/src/index.js

Every time I press "Add Item", a new item is appended. 
But the following code does not show the last item:
`this.carousel.goTo(this.state.items.length-1);`
One has to manually slide to the next item to find it hidden there.

Am I doing something wrong here? (I am new to React)
Thank you!

**Comment by waterrhett** [comment]
I realize this may be due to the async call to `setState`. 
Is that right? If so, how would I avoid this problem?
Thanks!

**Comment by sag1v** [comment]
@waterrhett You are spot on!

Indeed this is not related to `react-elastic-carousel` but to the fact that react state updates are async.

The class method setState has a second argument which is a callback that react triggers *after* the state is actually updated.

Try this:

```jsx
addItem = e => {
  this.setState(({ items }) => {
    const newItem = items.length + 1;
    const nextItems = [...items, newItem];
    return {
      items: nextItems
    };
  }, () => {
    console.log(this.state.items);
    this.carousel.goTo(this.state.items.length - 1);
  });
};
```

**Comment by waterrhett** [comment]
@sag1v This works perfectly!
Thank you so much (for teaching me React :)
