### ISSUE TITLE
Please add types for typescript

### ISSUE THREAD

**Issue by lorenzosjb** [sag1v/react-elastic-carousel#53]
Today is very important to have typescript compatibility, so please can you add it?
Thanks.

The import error says:

Could not find a declaration file for module 'react-elastic-carousel'. '/node_modules/react-elastic-carousel/dist/index.js' implicitly has an 'any' type.

Try npm install @types/react-elastic-carousel if it exists or add a new declaration (.d.ts) file containing declare module 'react-elastic-carousel';ts(7016)

**Comment by sag1v** [comment]
closing in favor of #34
