### ISSUE TITLE
What to do while loading

### ISSUE THREAD

**Issue by fastengineer** [sag1v/react-elastic-carousel#56]
It takes a 0.3 sn while loading, can we handle this? 

Is there any callback which we can use?

Thank you for awesome project!

**Comment by sag1v** [comment]
@fastengineer Loading of what?

**Comment by fastengineer** [comment]
The carausel, 

It takas a while to generate dom

**Comment by sag1v** [comment]
Can you please provide more details, like are you testing in dev mode or prod, maybe an example (codesandbox) or something similar?

**Comment by fastengineer** [comment]
Yes I am using SSR with next.js. I am rendering the slider as blank on server side, and I send objects on client side. Because I need client's timezone to filter objects.
You can check our recently developed website [the site in prod](https://cowork.today)
