### ISSUE TITLE
Can't resolve 'styled-components' in ../node_modules/react-elastic-carousel/dist

### ISSUE THREAD

**Issue by JuniorDiasOliveira** [sag1v/react-elastic-carousel#57]
**Describe the bug**
Asking for styled-components on a project without it.
```
./node_modules/react-elastic-carousel/dist/index.es.js
Module not found: Can't resolve 'styled-components' in /node_modules/react-elastic-carousel/dist'
```

**To Reproduce**
1. Install fresh in a project and follow the instructions in the docs to run.

**Expected behavior**
Works normally

**Additional context**
The project was created using typescript and material-ui

**Comment by sag1v** [comment]
Hi, This project is depended on styled-components. See [docs](https://github.com/sag1v/react-elastic-carousel#note)
