### ISSUE TITLE
Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by MonikaPikuzinska** [sag1v/react-elastic-carousel#59]
When I try to use this lib I get an error
![image](https://user-images.githubusercontent.com/57132665/87525474-d4216900-c689-11ea-9f48-d512d9fc5d87.png)

What should I do?

**Comment by sag1v** [comment]
Hi @MonikaPikuzinska , can you post a minimal example that reproduce this error?

**Comment by MonikaPikuzinska** [comment]
I get error when I try to click right arrow

**Comment by sag1v** [comment]
Can you please share some code?

**Comment by MonikaPikuzinska** [comment]
I don't know how but now everything works
