### ISSUE TITLE
Generated bundle includes dependencies

### ISSUE THREAD

**Issue by mAAdhaTTah** [sag1v/react-elastic-carousel#62]
**Describe the bug**
The generated bundle includes dependencies like `classNames` & the RO polyfill. As a result, the consumer's bundle can include those dependencies multiple times if they're used in other bundles.

**To Reproduce**
1. Install `react-elastic-carousel`.
2. Look at the `dist/index.js` file.
3. See the code for `classNames` & others.

**Expected behavior**
The bundle should only include the lib code so consumers can effectively dedupe tertiary dependencies.

**Comment by sag1v** [comment]
@mAAdhaTTah But what if the consumer doesn't use these two libraries? I'm not sure that each tertiary dependency should be a peer-dependency, its exhausting to install them manually.

**Comment by mAAdhaTTah** [comment]
@sag1v They shouldn't be peerDeps, just regular deps, like React & SC are.

**Comment by sag1v** [comment]
> @sag1v They shouldn't be peerDeps, just regular deps, like React & SC are.

Well, react and SC are peerDeps.

**Comment by sag1v** [comment]
@mAAdhaTTah I just remembered that rollup will bundle it ALL together via the `commonjs` plugin..

**Comment by mAAdhaTTah** [comment]
@sag1v Yeah, that's the cause. I believe if you move them to `deps`, the `external` plugin will make sure they're not bundled.

**Comment by sag1v** [comment]
@mAAdhaTTah nah, `external()` will ignore all peerDeps.  
If you see in `package.json`, the only entry in [dependencies](https://github.com/sag1v/react-elastic-carousel/blob/master/package.json#L113) is `react-swipeable` (my mistake for not including both `resize-observer` and `classnames` there as well), but i see that they are included in the bundle anyway.
I suspect that `rollup-plugin-node-resolve` and `rollup-plugin-commonjs` are forcing them to be part of the bundle (maybe they check for imports to decide).

I still think the end results is good (though achieved in a wrong way), if you look at the peerDeps array, you notice that none of them are bundled, but requires to get installed by the consumer. I don't think making consumers explicitly install `classnames` and `resize-observer-polyfill` is a good thing.

BTW, i just realised that we use `classnames` only in one place, i think of ditching it anyway.

**Comment by mAAdhaTTah** [comment]
@sag1v I agree that consumers should not need to install those libs to use the library. I disagree that the only alternative is to bundle non-peer-deps into the library. That's the behavior of the plugin you're using, but you could e.g. switch to [`auto-external`](https://www.npmjs.com/package/rollup-plugin-auto-external) or even using rollup's [`external`](https://rollupjs.org/guide/en/#external) to do it manually. Ultimately, my goal of opening this ticket is to remove those from the bundle so my installation can dedupe those dependencies appropriately.

**Comment by mAAdhaTTah** [comment]
Oh, to be clear, it's the behavior of [`rollup-plugin-peer-deps-external`](http://npm.im/rollup-plugin-peer-deps-external).

**Comment by sag1v** [comment]
@mAAdhaTTah I'm not sure i understand.

Whats do you think should be manually added to the `external` array? And what would happen if consumers wont include it manually?

For example, if we put `resize-observer-polyfill` in `external` but the consumer is not using it nor including it in their project, then where should it come from?

**Comment by mAAdhaTTah** [comment]
@sag1v If `resize-observer-polyfill` is in this library's package.json as a `dependency`, npm or yarn will install it automatically for this.

**Comment by sag1v** [comment]
Hmm something like this plugin?
https://www.npmjs.com/package/rollup-plugin-exclude-dependencies-from-bundle

**Comment by mAAdhaTTah** [comment]
Yeah that would work.

**Comment by sag1v** [comment]
I would welcome a PR 😁
Will be nice if you check that its actually working well for you...

**Comment by mAAdhaTTah** [comment]
Sure! I could probs take a look at this tomorrow.

**Comment by sag1v** [comment]
Thank you @mAAdhaTTah !

**Comment by mAAdhaTTah** [comment]
@sag1v Great, thank you!
