### ISSUE TITLE
Clicking the arrow buttons will submit a form.

### ISSUE THREAD

**Issue by superjose** [sag1v/react-elastic-carousel#63]
**Describe the bug**
The arrow buttons are submitting a form as they have no type specified.

**  Fix **
Just add `type={"button"}` in src/react-elastic-carousel/components/Arrow.js

This is an easy fix. Just need to add one line of code in Arrow.

**Comment by superjose** [comment]
I could make the pull request.

**Comment by sag1v** [comment]
Thanks @superjose ! A PR would be great :pray:

**Comment by superjose** [comment]
@sag1v Thanks to you 😊. This has been the best slider component that I found! (And I tried almost all of the ones found in npm!). Could you give me push access to the repo? Thx

**Comment by sag1v** [comment]
> @sag1v Thanks to you 😊. This has been the best slider component that I found! (And I tried almost all of the ones found in npm!). Could you give me push access to the repo? Thx 

I'm glad you like it 🙃
You don't need push access. Just fork the repo, make the change then open a pull request.

**Comment by superjose** [comment]
Oh sweet!! Thanks!

**Comment by sag1v** [comment]
Available as of version `0.7.0`
thanks @superjose
