### ISSUE TITLE
how to make next slide items partially visible

### ISSUE THREAD

**Issue by Shubhamg2595** [sag1v/react-elastic-carousel#73]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sag1v** [comment]
Hi @Shubhamg2595 
Can you please provide a description of what are you trying to achieve?

**Comment by Shubhamg2595** [comment]
I was trying to display portion of next slide as preview with current slide on focus.
Thanks for your reply. Achieved it with breakpoint prop and providing decimal values to itemsToShow prop.
Closing this issue.

**Comment by sag1v** [comment]
Decimals `itemsToShow` is not fully supported, well it wasn't until now (as of version `0.7.4`) 🙂
