### ISSUE TITLE
Problem with currentPage when replacing data sets (items)

### ISSUE THREAD

**Issue by GlutVonSmark** [sag1v/react-elastic-carousel#75]
Hi.

I have a view that uses the Carousel.
View allows me to provide the Carousel with different sets of data.
If I move the active page to let's say page number 3 on one set of data, (18 items showing 4 on screen)
when I switch the data to a different set I would like to be able to reset the activePage to be 0.

This also causes a bug when the data set that we move to has only 1 page but the activePage is set to something like 3.
We will not see all the items that we should see.

Created a sandbox to better explain this: 

Sandbox link:
https://codesandbox.io/s/react-elastic-carousel-forked-v7ziz?file=/src/index.js

To reproduce:

1. Click on the Data Set 3 button
2. Using the pagination move to the third page
3. Click on the Data Set 2 button
4. We have a new set of data/items but the currectPage piece of state is still on whatever was previously selected.
     Feature request would be to be able to manipulate currrentPage so can be reset with new data
5. Now to the bug: while still being on a third page of pagination, select Data Set 1.
6. You can only see 1 item being shown (for me it's the item number 3). This happens when the currentPage is higher than the number of pages for the current list of items.

Expected behaviour:
Carousel resets currentPage to the first page in this case

**Comment by sag1v** [comment]
Thanks @GlutVonSmark 
You think that using the `goTo` method can resolve your use case?

Something like this:
```jsx
function App() {
  const carouselRef = useRef();
  const [itemsNumber, setItemsNumber] = React.useState(4);

  const setNum = num => {
    setItemsNumber(num);
    carouselRef.current.goTo(0)
  }

  return (
    <div className="App">
      <div>
        <button onClick={() => setNum(3)}> Data Set 1 </button>
        <button onClick={() => setNum(18)}> Data Set 2 </button>
        <button onClick={() => setNum(21)}> Data Set 3 </button>
      </div>
      <div>Number of items to show: {itemsNumber}</div>
      <Carousel ref={carouselRef} itemsToShow={6}>{getItems(itemsNumber)}</Carousel>
    </div>
  );
}
```

**Comment by GlutVonSmark** [comment]
Would probably solve my problem.
I did with remounting of the carousel (adding new react key) when data props changes.

**Comment by sag1v** [comment]
Ok cool.
We can't do that inside the carousel (resetting the state when children chsnge) because it might break some use cases, like if someone wants to lazy add items...

**Comment by sag1v** [comment]
Hi, I'm closing this issue. If you still think theres something to be done in lib side feel free to re-open.
