### ISSUE TITLE
I am making a spfx web part with carousel, for that, I am using react-elastic-carousal, but while using it I am getting an error

### ISSUE THREAD

**Issue by prerak13** [sag1v/react-elastic-carousel#76]
**Describe the bug**

I am making a spfx web part with carousel, for that, I am using react-elastic-carousal, I installed it using npm.
 But when I try to use it in my spfx tsx file it is throwing error

**To Reproduce**

Carousel' cannot be used as a JSX component.   Its instance type 'ReactElasticCarousel' is not a valid JSX element.
    Type 'ReactElasticCarousel' is missing the following properties from type 'ElementClass': render, context, setState, forceUpdate, and 3 more.

**Expected behavior**
A component should load instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/25548089/91734652-d2275100-ebc8-11ea-8618-b3e051edcc55.png)

**Comment by sag1v** [comment]
Hi @prerak13 ,  Can you provide some code? hard to guess what went wrong

**Comment by prerak13** [comment]
I just used the <Carousel> </Carousel>  and got error which i specified on
mail.

I solved it by changing sourcecode of Carousel.ts file in which i changed

import * as react from react

Instead of
import react from react.

If you wish I want to send a pull req for this fix so it will be shown to
my profile.

**Comment by sag1v** [comment]
Oh so this is a typescript issue? 
Feel free to send a PR

**Comment by sag1v** [comment]
Fixed as of `v0.7.5`

**Comment by prerak13** [comment]
Someone already did.
