### ISSUE TITLE
[Feature Request] add prop for hideArrowsOnEnd

### ISSUE THREAD

**Issue by aarowman** [sag1v/react-elastic-carousel#80]
**Is your feature request related to a problem? Please describe.**
Currently we have `disableArrowsOnEnd` that still renders arrows, but they are disabled. It would be nice to have an option to hide them completely.

**Describe the solution you'd like**
Added boolean prop `hideArrowsOnEnd` (or change the `disableArrowsOnEnd` to a new prop with an enum for "show", "disable", "hide" with default "disable"), which causes the arrows to be hidden / not rendered at all

**Describe alternatives you've considered**
Manually using `renderArrows` function to check if on an end page or not, then rendering a placeholder empty div

**Additional context**
A placeholder would likely be needed to keep the spacing balanced for the cards.

Related to issue #36 and PR #42

**Comment by sag1v** [comment]
Hi @aarowman, I think we can achieve that by simply adding a css class?

Something like:
```css
.rec-arrow:disabled {
    visibility: hidden;
}
```

This will also keep the space

**Comment by aarowman** [comment]
@sag1v Sure, let's give it a shot! Good idea.. 
Are you suggesting doing that in the client project? Or doing that here in this repo as the solution when the prop is added?

**Comment by sag1v** [comment]
> @sag1v Sure, let's give it a shot! Good idea.. 
> Are you suggesting doing that in the client project? Or doing that here in this repo as the solution when the prop is added?

@aarowman I mean the consumer can do that, instead of passing a prop, he/she can just create this rule.

**Comment by aarowman** [comment]
Makes sense. The downside is that the consumer has to determine the
classname of the button. If they don't render it themselves (or if they
don't need a class otherwise), then it's more complicated.

For me, it's good enough since I'm creating my own buttons with a class so
I can just use that.
The `:disabled` part is a good tip

**Comment by sag1v** [comment]
@aarowman 
Not sure i understand this part

>  The downside is that the consumer has to determine the classname of the button. If they don't render it themselves (or if they don't need a class otherwise), then it's more complicated.

**Comment by sag1v** [comment]
@aarowman I'm going to close this. Feel free to re-open if you think there is something to do from the lib side

**Comment by aarowman** [comment]
> I realised that not everyone knows that `react-elastic-carousel` expose some public css classes as part of it's API, so i added this styling section in the docs.
> https://sag1v.github.io/react-elastic-carousel/#styling

I was not aware of this part. 

What I was saying above is that the workaround solution is basically to use the hard-coded class name to hide it. This is a decent workaround, but still has a risk if the class name changes. Also, if the client renders the arrows themselves, then the class name would be different or missing altogether, but hopefully they would add it to make it work.

Considering the styling is exposed, then that should hopefully be sufficient. It would be pretty easy to add to this library though and just do the CSS there instead so the client doesn't have to, but maybe not a big enough issue.

**Comment by sag1v** [comment]
@aarowman All class names with the rec- prefix won't change as i consider them part of the library API, if they change that means a major version bump (api break), no different than props.

BTW, these classes have no styling, they are just there for injecting style from outside. Like in this case.

**Comment by aarowman** [comment]
Ok great! Yeah that wasn't clear to me from the docs at first. Now it's
more clear, thanks!
