### ISSUE TITLE
Create option, or permanently disable the blue outline when element is focused

### ISSUE THREAD

**Issue by Camlgiles** [sag1v/react-elastic-carousel#81]
![Screen Shot 2020-09-23 at 1 30 13 PM](https://user-images.githubusercontent.com/47339561/94066589-8a4bb200-fda1-11ea-885a-d53b43348175.png)

I can't disable the blue outline when a carousel element is focused. would be nice to have an option to disable this highlight.

**Comment by sag1v** [comment]
It's just the default browser's styling, it can be disabled with css.

You can create a rule that disables the `outline` for any nested elements under the carousel (or any other carousel element):

```css
.rec-carousel *:focus {
    outline: none;
}
```

**Comment by Camlgiles** [comment]
worked perfectly. thank you!
