### ISSUE TITLE
realtime swipe/drag

### ISSUE THREAD

**Issue by Multi-Thinker** [sag1v/react-elastic-carousel#87]
**Is your feature request related to a problem? Please describe.**
currently, this slider shows a bad animation and drag/swipe handler, if you try to swipe https://sag1v.github.io/react-elastic-carousel/ you have to remove mouse for it to change. 

**Describe the solution you'd like**
Most elastic carousel uses realtime swipe/drag, which you hold one card and drag to left or right the slider moves with it. also is it possible to have both left, right overflown as a feature or options (let say you have some company brands the first to 2nd last look, okay the last one is half sliced indicating a swipe) 
**Describe alternatives you've considered**
using different lib

**Additional context**
some ideas: 
![image](https://user-images.githubusercontent.com/9819390/94783081-99f07980-03e5-11eb-8652-3b3ad700f2de.png)
![image](https://user-images.githubusercontent.com/9819390/94783103-a4127800-03e5-11eb-80c9-fc93680e4a63.png)

**Comment by sag1v** [comment]
Hi @Multi-Thinker 
1. Realtime swipe/drag - This requires a different approach via the swipe mechanism, it is doable but needs some time to implement. 
2. Overflow items - Did you try providing a decimal or a float as `itemsToshow`? 

for example 

```jsx
<Carousel itemsToShow={2.3}>
  <Item>1</Item>
  <Item>2</Item>
  <Item>3</Item>
  <Item>4</Item>
  <Item>5</Item>
  <Item>6</Item>
</Carousel>
```

**Comment by sag1v** [comment]
@Multi-Thinker Realtime swiping was added, install latest version to get it 🙂

**Comment by Multi-Thinker** [comment]
You Rock!! I just tried it now after seeing PR merged. :)) it works flawlessly. are you open for PR? i'd love to keep this lib rocking

**Comment by sag1v** [comment]
PR's are always welcome 🙏🏽
