### ISSUE TITLE
Add `onKeyDown` callback for items

### ISSUE THREAD

**Issue by aarowman** [sag1v/react-elastic-carousel#88]
**Is your feature request related to a problem? Please describe.**
Since the a11y features were added, the item has a wrapper div that gets `tabIndex={0}`, which generally requires removing tabIndex from the children. Because of this, the `onKeyDown` event is not triggered on the child.

Note: my specific use case is using a `Link`. The `onClick` event is still triggered, but I cannot get the "enter" key press to open the link when the item is focused, without adding an extra tabIndex.
It worked before the a11y features, since the `Link` itself could get focus when clicking tab, but now I have to set `tabIndex={-1}` so it doesn't take 2 tabs to get to it.

**Describe the solution you'd like**
Add a callback for `itemKeyDown` that can be called (should pass the event/item itself to access child properties), or call the `onKeyDown` on the item wrapper that calls the child `onKeyDown` if it exists.

**Describe alternatives you've considered**
Revert back to old carousel library version before a11y, and add `tabIndex` to the items myself. This is undesirable because then EVERY element gets tabs, not just the visible ones. It also means staying behind on an old version.

**Additional context**
As mentioned above, the `onClick` is still working down on the child. This is likely default browser behavior. The `onKeyDown` event is based on which element has focus, which comes from the tabIndex if a normal div.

**Comment by sag1v** [comment]
Thanks @aarowman !
Can you please create a minimal [sandbox](https://codesandbox.io/s/21o46mkwnr) example so i can tinker with?

**Comment by sag1v** [comment]
@aarowman I made some changes, now the `tabIndex` is injected to the Items, visible items gets `0` and none visible items gets `-1`. You can grab that `tabIndex` and pass it to whatever nested element you want (or the root element of the Item).

This way you as a consumer has the control on what is being focused (or not).

I also added a prop - `autoTabIndexVisibleItems` which defaults to `true` but you can set to `false` to opt-out of this behaviour.

**Comment by aarowman** [comment]
@sag1v Sounds like a good solution. I'm excited to give it a try!

**Comment by aarowman** [comment]
@sag1v What does the source look like for your playground example? It just shows `ItemWithLink`. Is that a `<div>` with a nested `<a>` tag? I know it's just example code, but I'd be interested to see the true nature of the components in the examples too.

**Comment by sag1v** [comment]
@aarowman You can see it [here](https://github.com/sag1v/react-elastic-carousel/blob/master/src/docs/components/ItemWithLink.js)

Attaching the code itself for visibility:

```jsx
const ItemWithLink = ({ tabIndex, text }) => (
  <Item>
    <a href={`#link${text}`} tabIndex={tabIndex}>
      {text}
    </a>
  </Item>
);
```

**Comment by aarowman** [comment]
Looks good to me!
