### ISSUE TITLE
Arrow hiding on breakpoint

### ISSUE THREAD

**Issue by CharlieJ213** [sag1v/react-elastic-carousel#91]
I cannot at the moment find a way of hiding the arrows at a max screen width. I have tried including it in the BreakPoints object. I have tried it with css @media tags targeting the .rec.rec-arrow classes and they still won't hide.

Add the option to change the showArrows prop in the breakPoints class

**Comment by CharlieJ213** [comment]
I closed it because I was just changing the button's display attribute to none, but then realised there was also an issue with that then hiding the pagination dots.

I have copied the exact same style examples from the actual website and it won't work in my own project. I am importing the css file correctly, I don't understand what is going on and why I can't style it

**Comment by sag1v** [comment]
@CharlieJ213 Why would you want to base your hide arrows condition on screen width? What if you you are on a max screen width but still have the ability to scroll the carousel window, if you hide the arrows the user wont be able to scroll to the next items.

**Comment by sag1v** [comment]
@CharlieJ213 I realised that you might want to pass other props via a breakpoint. Although you can hook to the `onResize` callback and change the props, i think  REC should provide that out of the box.

So i'm going to add this capability that **ANY** prop can be passed directly to REC or via a break point. Keep in mind that i'm merging them so a prop passed via a breakpoint will override a direct prop.

**Comment by sag1v** [comment]
Available as of version `0.9.0`

**Comment by CharlieJ213** [comment]
I'm working on a web project which is meant to be a mobile first design and the arrows don't suit the designs we have, but they need to be there for desktop

**Comment by sag1v** [comment]
> I'm working on a web project which is meant to be a mobile first design and the arrows don't suit the designs we have, but they need to be there for desktop

Got it. 
Try latest version, should work now.

**Comment by pejman1** [comment]
> > I'm working on a web project which is meant to be a mobile first design and the arrows don't suit the designs we have, but they need to be there for desktop
> 
> Got it.
> Try latest version, should work now.

Hi, changes in last version causes new issue . while you change the state of windows to fullscreen carousel does not response the new window's size. I tested in google chrome windows 10. this issue is not in version 0.8.1

**Comment by sag1v** [comment]
@pejman1 Thank you.
Can you please open a new issue (referencing this one) with a sandbox link that demonstrate the problem?

**Comment by sag1v** [comment]
@pejman1 I managed to reproduce it, should be fixed in version `0.9.1`

**Comment by pejman1** [comment]
> @pejman1 I managed to reproduce it, should be fixed in version `0.9.1`

thank you so much . it's fixed
