### ISSUE TITLE
renderPagination page type number, not array

### ISSUE THREAD

**Issue by djsladi** [sag1v/react-elastic-carousel#93]
**Describe the bug**
Type of "page" should be "array", not "number" in RenderPaginationProps 

**To Reproduce**
Write the renderPagination example to Carousel-component and observe, that pages.map is not allowed on type "number"

**Screenshots**
![image](https://user-images.githubusercontent.com/39775012/96960821-03a70380-150c-11eb-9d37-db26dff83afe.png)

**Comment by djsladi** [comment]
Changing pages: number; to pages: [] on index.d.ts fixes the issue.

**Comment by sag1v** [comment]
Thanks @djsladi !

**Comment by sag1v** [comment]
@djsladi Should be fixed in version `0.9.1`
