### ISSUE TITLE
disable transition while resizing the window

### ISSUE THREAD

**Issue by pejman1** [sag1v/react-elastic-carousel#94]
**Is your feature request related to a problem? Please describe.**

When we are in slide 2 or more , resizing the window and adding more items as a responsive page  to slide cause play transition and moving items in the screen. 
* it's not happening in slide 1 of the carousel 

**Describe the solution you'd like**

I want a carousel like apple store in mac. transition plays just in changing slides not in adding items while resizing window

**Comment by sag1v** [comment]
Thanks @pejman1. Can you try installing version `0.9.2-beta` or just use the `next` tag and tell me if this is sorted?

**Comment by pejman1** [comment]
> Thanks @pejman1. Can you try installing version `0.9.2-beta` or just use the `next` tag and tell me if this is sorted?

It is fixed in version 0.9.2, great work.  thank you so much

**Comment by sag1v** [comment]
You can use the normal `latest` version instead of the beta `next`. So this is fixed as of `v0.9.3`
