### ISSUE TITLE
Types are not exported

### ISSUE THREAD

**Issue by thibaultadet** [sag1v/react-elastic-carousel#95]
**Is your feature request related to a problem? Please describe.**
When using Typescript, the types are not found. They are not exported from the index.
It does not throw an error when running but when linting.

**Describe the solution you'd like**
It would be great to export the types so they can be used with Typescript without throwing errors.

And by the way thanks for this great package 😃

**Comment by sag1v** [comment]
Thanks @thibaultadet !
So how do we import/export them?
Im not a TS user so never done this before.

**Comment by thibaultadet** [comment]
Just by adding `export` 😉 
and people will be able to import it like so :
`import { RenderArrowProps, RenderPaginationProps } from "react-elastic-carousel"`

```typescript
export type RenderArrowProps = {
  type: "PREV" | "NEXT";
  onClick: () => void;
  isEdge: boolean;
};

export type RenderPaginationProps = {
  pages: number[];
  activePage: number;
  // The onClick event that sets the state of the carousel and sends
  // it to a specific page.
  onClick: (indicatorId: string) => void;
};

export type ItemObject = {
  // Children's props
  object: any;
  index: number;
};

export type Breakpoint = {
  itemsToScroll: number;
  itemsToShow: number;
};
```

**Comment by sag1v** [comment]
Wait i thought this is [already supported](https://github.com/sag1v/react-elastic-carousel/blob/master/src/react-elastic-carousel/index.d.ts#L28).

Can't we just do:

```jsx
import { ReactElasticCarouselProps } from 'react-elastic-carousel'

// use it
ReactElasticCarouselProps.RenderPaginationProps
ReactElasticCarouselProps.RenderArrowProps
...
```

**Comment by sag1v** [comment]
@thibaultadet Can you confirm that what i wrote in [this comment](95#issuecomment-717439921) is sufficient?
I want to release a new version with some bug fixes and i want to know if i need to make any change for this issue.

**Comment by thibaultadet** [comment]
@sag1v It doesn't work because `ReactElasticCarouselProps` is an interface. I'm not a Typescript expert but for your solution to work you would need to create a `namespace`, something like :
```typescript
namespace ReactElasticCarousel {
  type RenderArrowProps = {
    type: "PREV" | "NEXT";
    onClick: () => void;
    isEdge: boolean;
  };
...
}
```

and then you could call :
```typescript
import { ReactElasticCarousel } from 'react-elastic-carousel'

// use it
ReactElasticCarousel.RenderPaginationProps
ReactElasticCarousel.RenderArrowProps
...
```

**Comment by sag1v** [comment]
Types are now exported in version `0.9.3`
